# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotnameform.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_plotNameForm(object):
    def setupUi(self, plotNameForm):
        plotNameForm.setObjectName(_fromUtf8("plotNameForm"))
        plotNameForm.resize(840, 614)
        self.file1Lbl = QtGui.QLabel(plotNameForm)
        self.file1Lbl.setGeometry(QtCore.QRect(10, 50, 290, 20))
        font = QtGui.QFont()
        self.file1Lbl.setFont(font)
        self.file1Lbl.setWordWrap(False)
        self.file1Lbl.setObjectName(_fromUtf8("file1Lbl"))
        self.PlotLegendLbl = QtGui.QLabel(plotNameForm)
        self.PlotLegendLbl.setGeometry(QtCore.QRect(370, 20, 70, 20))
        font = QtGui.QFont()
        self.PlotLegendLbl.setFont(font)
        self.PlotLegendLbl.setWordWrap(False)
        self.PlotLegendLbl.setObjectName(_fromUtf8("PlotLegendLbl"))
        self.lineColorCBox1 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox1.setGeometry(QtCore.QRect(740, 50, 90, 20))
        self.lineColorCBox1.setObjectName(_fromUtf8("lineColorCBox1"))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.lineColorCBox1.addItem(_fromUtf8(""))
        self.file7Lbl = QtGui.QLabel(plotNameForm)
        self.file7Lbl.setGeometry(QtCore.QRect(10, 350, 290, 20))
        font = QtGui.QFont()
        self.file7Lbl.setFont(font)
        self.file7Lbl.setWordWrap(False)
        self.file7Lbl.setObjectName(_fromUtf8("file7Lbl"))
        self.textLabel1 = QtGui.QLabel(plotNameForm)
        self.textLabel1.setGeometry(QtCore.QRect(470, 20, 60, 20))
        font = QtGui.QFont()
        self.textLabel1.setFont(font)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.LineWidthLbl_2_2 = QtGui.QLabel(plotNameForm)
        self.LineWidthLbl_2_2.setGeometry(QtCore.QRect(750, 20, 60, 20))
        font = QtGui.QFont()
        self.LineWidthLbl_2_2.setFont(font)
        self.LineWidthLbl_2_2.setWordWrap(False)
        self.LineWidthLbl_2_2.setObjectName(_fromUtf8("LineWidthLbl_2_2"))
        self.file5Lbl = QtGui.QLabel(plotNameForm)
        self.file5Lbl.setGeometry(QtCore.QRect(10, 250, 290, 20))
        font = QtGui.QFont()
        self.file5Lbl.setFont(font)
        self.file5Lbl.setWordWrap(False)
        self.file5Lbl.setObjectName(_fromUtf8("file5Lbl"))
        self.lineColorCBox6 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox6.setGeometry(QtCore.QRect(740, 300, 90, 20))
        self.lineColorCBox6.setObjectName(_fromUtf8("lineColorCBox6"))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox6.addItem(_fromUtf8(""))
        self.lineColorCBox3 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox3.setGeometry(QtCore.QRect(740, 150, 90, 20))
        self.lineColorCBox3.setObjectName(_fromUtf8("lineColorCBox3"))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox3.addItem(_fromUtf8(""))
        self.lineColorCBox2 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox2.setGeometry(QtCore.QRect(740, 100, 90, 20))
        self.lineColorCBox2.setObjectName(_fromUtf8("lineColorCBox2"))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.lineColorCBox2.addItem(_fromUtf8(""))
        self.PointSizeLbl = QtGui.QLabel(plotNameForm)
        self.PointSizeLbl.setGeometry(QtCore.QRect(650, 10, 40, 30))
        font = QtGui.QFont()
        self.PointSizeLbl.setFont(font)
        self.PointSizeLbl.setWordWrap(False)
        self.PointSizeLbl.setObjectName(_fromUtf8("PointSizeLbl"))
        self.lineColorCBox7 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox7.setGeometry(QtCore.QRect(740, 350, 90, 20))
        self.lineColorCBox7.setObjectName(_fromUtf8("lineColorCBox7"))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox7.addItem(_fromUtf8(""))
        self.lineColorCBox5 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox5.setGeometry(QtCore.QRect(740, 250, 90, 20))
        self.lineColorCBox5.setObjectName(_fromUtf8("lineColorCBox5"))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.lineColorCBox5.addItem(_fromUtf8(""))
        self.file6Lbl = QtGui.QLabel(plotNameForm)
        self.file6Lbl.setGeometry(QtCore.QRect(10, 300, 290, 20))
        font = QtGui.QFont()
        self.file6Lbl.setFont(font)
        self.file6Lbl.setWordWrap(False)
        self.file6Lbl.setObjectName(_fromUtf8("file6Lbl"))
        self.LineWidthLbl_2 = QtGui.QLabel(plotNameForm)
        self.LineWidthLbl_2.setGeometry(QtCore.QRect(700, 10, 38, 40))
        font = QtGui.QFont()
        self.LineWidthLbl_2.setFont(font)
        self.LineWidthLbl_2.setWordWrap(False)
        self.LineWidthLbl_2.setObjectName(_fromUtf8("LineWidthLbl_2"))
        self.PointsLbl = QtGui.QLabel(plotNameForm)
        self.PointsLbl.setGeometry(QtCore.QRect(550, 20, 65, 20))
        font = QtGui.QFont()
        self.PointsLbl.setFont(font)
        self.PointsLbl.setWordWrap(False)
        self.PointsLbl.setObjectName(_fromUtf8("PointsLbl"))
        self.lineColorCBox4 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox4.setGeometry(QtCore.QRect(740, 200, 90, 20))
        self.lineColorCBox4.setObjectName(_fromUtf8("lineColorCBox4"))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.lineColorCBox4.addItem(_fromUtf8(""))
        self.plotOrder6 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder6.setGeometry(QtCore.QRect(480, 300, 20, 22))
        font = QtGui.QFont()
        self.plotOrder6.setFont(font)
        self.plotOrder6.setObjectName(_fromUtf8("plotOrder6"))
        self.plotOrder7 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder7.setGeometry(QtCore.QRect(480, 350, 20, 22))
        font = QtGui.QFont()
        self.plotOrder7.setFont(font)
        self.plotOrder7.setObjectName(_fromUtf8("plotOrder7"))
        self.pointsCBox3 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox3.setGeometry(QtCore.QRect(510, 150, 120, 20))
        self.pointsCBox3.setObjectName(_fromUtf8("pointsCBox3"))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox3.addItem(_fromUtf8(""))
        self.pointsCBox4 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox4.setGeometry(QtCore.QRect(510, 200, 120, 20))
        self.pointsCBox4.setObjectName(_fromUtf8("pointsCBox4"))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox4.addItem(_fromUtf8(""))
        self.pointsCBox5 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox5.setGeometry(QtCore.QRect(510, 250, 120, 20))
        self.pointsCBox5.setObjectName(_fromUtf8("pointsCBox5"))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox5.addItem(_fromUtf8(""))
        self.pointsCBox6 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox6.setGeometry(QtCore.QRect(510, 300, 120, 20))
        self.pointsCBox6.setObjectName(_fromUtf8("pointsCBox6"))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.pointsCBox6.addItem(_fromUtf8(""))
        self.file8Lbl = QtGui.QLabel(plotNameForm)
        self.file8Lbl.setGeometry(QtCore.QRect(10, 400, 290, 20))
        font = QtGui.QFont()
        self.file8Lbl.setFont(font)
        self.file8Lbl.setWordWrap(False)
        self.file8Lbl.setObjectName(_fromUtf8("file8Lbl"))
        self.file3Lbl = QtGui.QLabel(plotNameForm)
        self.file3Lbl.setGeometry(QtCore.QRect(10, 150, 290, 20))
        font = QtGui.QFont()
        self.file3Lbl.setFont(font)
        self.file3Lbl.setWordWrap(False)
        self.file3Lbl.setObjectName(_fromUtf8("file3Lbl"))
        self.plotOrder1 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder1.setGeometry(QtCore.QRect(480, 50, 20, 22))
        font = QtGui.QFont()
        self.plotOrder1.setFont(font)
        self.plotOrder1.setObjectName(_fromUtf8("plotOrder1"))
        self.plotOrder2 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder2.setGeometry(QtCore.QRect(480, 100, 20, 22))
        font = QtGui.QFont()
        self.plotOrder2.setFont(font)
        self.plotOrder2.setObjectName(_fromUtf8("plotOrder2"))
        self.plotOrder3 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder3.setGeometry(QtCore.QRect(480, 150, 20, 22))
        font = QtGui.QFont()
        self.plotOrder3.setFont(font)
        self.plotOrder3.setObjectName(_fromUtf8("plotOrder3"))
        self.plotOrder4 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder4.setGeometry(QtCore.QRect(480, 200, 20, 22))
        font = QtGui.QFont()
        self.plotOrder4.setFont(font)
        self.plotOrder4.setObjectName(_fromUtf8("plotOrder4"))
        self.plotOrder5 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder5.setGeometry(QtCore.QRect(480, 250, 20, 22))
        font = QtGui.QFont()
        self.plotOrder5.setFont(font)
        self.plotOrder5.setObjectName(_fromUtf8("plotOrder5"))
        self.pointSizeCBox1 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox1.setGeometry(QtCore.QRect(640, 50, 50, 20))
        self.pointSizeCBox1.setObjectName(_fromUtf8("pointSizeCBox1"))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox1.addItem(_fromUtf8(""))
        self.pointSizeCBox2 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox2.setGeometry(QtCore.QRect(640, 100, 50, 20))
        self.pointSizeCBox2.setObjectName(_fromUtf8("pointSizeCBox2"))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox2.addItem(_fromUtf8(""))
        self.pointSizeCBox3 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox3.setGeometry(QtCore.QRect(640, 150, 50, 20))
        self.pointSizeCBox3.setObjectName(_fromUtf8("pointSizeCBox3"))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox3.addItem(_fromUtf8(""))
        self.pointSizeCBox4 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox4.setGeometry(QtCore.QRect(640, 200, 50, 20))
        self.pointSizeCBox4.setObjectName(_fromUtf8("pointSizeCBox4"))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox4.addItem(_fromUtf8(""))
        self.pointSizeCBox5 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox5.setGeometry(QtCore.QRect(640, 250, 50, 20))
        self.pointSizeCBox5.setObjectName(_fromUtf8("pointSizeCBox5"))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox5.addItem(_fromUtf8(""))
        self.pointSizeCBox6 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox6.setGeometry(QtCore.QRect(640, 300, 50, 20))
        self.pointSizeCBox6.setObjectName(_fromUtf8("pointSizeCBox6"))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox6.addItem(_fromUtf8(""))
        self.pointSizeCBox7 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox7.setGeometry(QtCore.QRect(640, 350, 50, 20))
        self.pointSizeCBox7.setObjectName(_fromUtf8("pointSizeCBox7"))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.pointSizeCBox7.addItem(_fromUtf8(""))
        self.lineWidthCBox1 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox1.setGeometry(QtCore.QRect(700, 50, 30, 20))
        self.lineWidthCBox1.setObjectName(_fromUtf8("lineWidthCBox1"))
        self.lineWidthCBox1.addItem(_fromUtf8(""))
        self.lineWidthCBox1.addItem(_fromUtf8(""))
        self.lineWidthCBox1.addItem(_fromUtf8(""))
        self.lineWidthCBox1.addItem(_fromUtf8(""))
        self.lineWidthCBox1.addItem(_fromUtf8(""))
        self.lineWidthCBox1.addItem(_fromUtf8(""))
        self.lineWidthCBox2 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox2.setGeometry(QtCore.QRect(700, 100, 30, 20))
        self.lineWidthCBox2.setObjectName(_fromUtf8("lineWidthCBox2"))
        self.lineWidthCBox2.addItem(_fromUtf8(""))
        self.lineWidthCBox2.addItem(_fromUtf8(""))
        self.lineWidthCBox2.addItem(_fromUtf8(""))
        self.lineWidthCBox2.addItem(_fromUtf8(""))
        self.lineWidthCBox2.addItem(_fromUtf8(""))
        self.lineWidthCBox2.addItem(_fromUtf8(""))
        self.lineWidthCBox3 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox3.setGeometry(QtCore.QRect(700, 150, 30, 20))
        self.lineWidthCBox3.setObjectName(_fromUtf8("lineWidthCBox3"))
        self.lineWidthCBox3.addItem(_fromUtf8(""))
        self.lineWidthCBox3.addItem(_fromUtf8(""))
        self.lineWidthCBox3.addItem(_fromUtf8(""))
        self.lineWidthCBox3.addItem(_fromUtf8(""))
        self.lineWidthCBox3.addItem(_fromUtf8(""))
        self.lineWidthCBox3.addItem(_fromUtf8(""))
        self.lineWidthCBox4 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox4.setGeometry(QtCore.QRect(700, 200, 30, 20))
        self.lineWidthCBox4.setObjectName(_fromUtf8("lineWidthCBox4"))
        self.lineWidthCBox4.addItem(_fromUtf8(""))
        self.lineWidthCBox4.addItem(_fromUtf8(""))
        self.lineWidthCBox4.addItem(_fromUtf8(""))
        self.lineWidthCBox4.addItem(_fromUtf8(""))
        self.lineWidthCBox4.addItem(_fromUtf8(""))
        self.lineWidthCBox4.addItem(_fromUtf8(""))
        self.lineWidthCBox5 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox5.setGeometry(QtCore.QRect(700, 250, 30, 20))
        self.lineWidthCBox5.setObjectName(_fromUtf8("lineWidthCBox5"))
        self.lineWidthCBox5.addItem(_fromUtf8(""))
        self.lineWidthCBox5.addItem(_fromUtf8(""))
        self.lineWidthCBox5.addItem(_fromUtf8(""))
        self.lineWidthCBox5.addItem(_fromUtf8(""))
        self.lineWidthCBox5.addItem(_fromUtf8(""))
        self.lineWidthCBox5.addItem(_fromUtf8(""))
        self.lineWidthCBox6 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox6.setGeometry(QtCore.QRect(700, 300, 30, 20))
        self.lineWidthCBox6.setObjectName(_fromUtf8("lineWidthCBox6"))
        self.lineWidthCBox6.addItem(_fromUtf8(""))
        self.lineWidthCBox6.addItem(_fromUtf8(""))
        self.lineWidthCBox6.addItem(_fromUtf8(""))
        self.lineWidthCBox6.addItem(_fromUtf8(""))
        self.lineWidthCBox6.addItem(_fromUtf8(""))
        self.lineWidthCBox6.addItem(_fromUtf8(""))
        self.lineWidthCBox7 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox7.setGeometry(QtCore.QRect(700, 350, 30, 20))
        self.lineWidthCBox7.setObjectName(_fromUtf8("lineWidthCBox7"))
        self.lineWidthCBox7.addItem(_fromUtf8(""))
        self.lineWidthCBox7.addItem(_fromUtf8(""))
        self.lineWidthCBox7.addItem(_fromUtf8(""))
        self.lineWidthCBox7.addItem(_fromUtf8(""))
        self.lineWidthCBox7.addItem(_fromUtf8(""))
        self.lineWidthCBox7.addItem(_fromUtf8(""))
        self.file4Lbl = QtGui.QLabel(plotNameForm)
        self.file4Lbl.setGeometry(QtCore.QRect(10, 200, 290, 20))
        font = QtGui.QFont()
        self.file4Lbl.setFont(font)
        self.file4Lbl.setWordWrap(False)
        self.file4Lbl.setObjectName(_fromUtf8("file4Lbl"))
        self.file3Edit = QtGui.QLineEdit(plotNameForm)
        self.file3Edit.setGeometry(QtCore.QRect(310, 150, 160, 23))
        font = QtGui.QFont()
        self.file3Edit.setFont(font)
        self.file3Edit.setObjectName(_fromUtf8("file3Edit"))
        self.file4Edit = QtGui.QLineEdit(plotNameForm)
        self.file4Edit.setGeometry(QtCore.QRect(310, 200, 160, 23))
        font = QtGui.QFont()
        self.file4Edit.setFont(font)
        self.file4Edit.setObjectName(_fromUtf8("file4Edit"))
        self.file5Edit = QtGui.QLineEdit(plotNameForm)
        self.file5Edit.setGeometry(QtCore.QRect(310, 250, 160, 23))
        font = QtGui.QFont()
        self.file5Edit.setFont(font)
        self.file5Edit.setObjectName(_fromUtf8("file5Edit"))
        self.file6Edit = QtGui.QLineEdit(plotNameForm)
        self.file6Edit.setGeometry(QtCore.QRect(310, 300, 160, 23))
        font = QtGui.QFont()
        self.file6Edit.setFont(font)
        self.file6Edit.setObjectName(_fromUtf8("file6Edit"))
        self.file2Lbl = QtGui.QLabel(plotNameForm)
        self.file2Lbl.setGeometry(QtCore.QRect(10, 100, 290, 20))
        font = QtGui.QFont()
        self.file2Lbl.setFont(font)
        self.file2Lbl.setWordWrap(False)
        self.file2Lbl.setObjectName(_fromUtf8("file2Lbl"))
        self.file2Edit = QtGui.QLineEdit(plotNameForm)
        self.file2Edit.setGeometry(QtCore.QRect(310, 100, 160, 23))
        font = QtGui.QFont()
        self.file2Edit.setFont(font)
        self.file2Edit.setObjectName(_fromUtf8("file2Edit"))
        self.pointsCBox7 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox7.setGeometry(QtCore.QRect(510, 350, 120, 20))
        self.pointsCBox7.setObjectName(_fromUtf8("pointsCBox7"))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.pointsCBox7.addItem(_fromUtf8(""))
        self.file7Edit = QtGui.QLineEdit(plotNameForm)
        self.file7Edit.setGeometry(QtCore.QRect(310, 350, 160, 23))
        font = QtGui.QFont()
        self.file7Edit.setFont(font)
        self.file7Edit.setObjectName(_fromUtf8("file7Edit"))
        self.file1Edit = QtGui.QLineEdit(plotNameForm)
        self.file1Edit.setGeometry(QtCore.QRect(310, 50, 160, 23))
        font = QtGui.QFont()
        self.file1Edit.setFont(font)
        self.file1Edit.setText(_fromUtf8(""))
        self.file1Edit.setObjectName(_fromUtf8("file1Edit"))
        self.plotOrder8 = QtGui.QLineEdit(plotNameForm)
        self.plotOrder8.setGeometry(QtCore.QRect(480, 400, 20, 22))
        font = QtGui.QFont()
        self.plotOrder8.setFont(font)
        self.plotOrder8.setObjectName(_fromUtf8("plotOrder8"))
        self.pointsCBox8 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox8.setGeometry(QtCore.QRect(510, 400, 120, 20))
        self.pointsCBox8.setObjectName(_fromUtf8("pointsCBox8"))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointsCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8 = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBox8.setGeometry(QtCore.QRect(640, 400, 50, 20))
        self.pointSizeCBox8.setObjectName(_fromUtf8("pointSizeCBox8"))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.pointSizeCBox8.addItem(_fromUtf8(""))
        self.lineWidthCBox8 = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBox8.setGeometry(QtCore.QRect(700, 400, 30, 20))
        self.lineWidthCBox8.setObjectName(_fromUtf8("lineWidthCBox8"))
        self.lineWidthCBox8.addItem(_fromUtf8(""))
        self.lineWidthCBox8.addItem(_fromUtf8(""))
        self.lineWidthCBox8.addItem(_fromUtf8(""))
        self.lineWidthCBox8.addItem(_fromUtf8(""))
        self.lineWidthCBox8.addItem(_fromUtf8(""))
        self.lineWidthCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8 = QtGui.QComboBox(plotNameForm)
        self.lineColorCBox8.setGeometry(QtCore.QRect(740, 400, 90, 20))
        self.lineColorCBox8.setObjectName(_fromUtf8("lineColorCBox8"))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.lineColorCBox8.addItem(_fromUtf8(""))
        self.file8Edit = QtGui.QLineEdit(plotNameForm)
        self.file8Edit.setGeometry(QtCore.QRect(310, 400, 160, 23))
        font = QtGui.QFont()
        self.file8Edit.setFont(font)
        self.file8Edit.setObjectName(_fromUtf8("file8Edit"))
        self.pointsCBox1 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox1.setGeometry(QtCore.QRect(510, 50, 120, 20))
        self.pointsCBox1.setObjectName(_fromUtf8("pointsCBox1"))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox1.addItem(_fromUtf8(""))
        self.pointsCBox2 = QtGui.QComboBox(plotNameForm)
        self.pointsCBox2.setGeometry(QtCore.QRect(510, 100, 120, 20))
        self.pointsCBox2.setObjectName(_fromUtf8("pointsCBox2"))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.pointsCBox2.addItem(_fromUtf8(""))
        self.lineWidthCBoxChangeAll = QtGui.QComboBox(plotNameForm)
        self.lineWidthCBoxChangeAll.setGeometry(QtCore.QRect(700, 460, 30, 20))
        self.lineWidthCBoxChangeAll.setObjectName(_fromUtf8("lineWidthCBoxChangeAll"))
        self.lineWidthCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineWidthCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineWidthCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineWidthCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineWidthCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineWidthCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll = QtGui.QComboBox(plotNameForm)
        self.lineColorCBoxChangeAll.setGeometry(QtCore.QRect(740, 460, 90, 20))
        self.lineColorCBoxChangeAll.setObjectName(_fromUtf8("lineColorCBoxChangeAll"))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.lineColorCBoxChangeAll.addItem(_fromUtf8(""))
        self.y_axisPositionLbl = QtGui.QLabel(plotNameForm)
        self.y_axisPositionLbl.setEnabled(False)
        self.y_axisPositionLbl.setGeometry(QtCore.QRect(630, 510, 90, 20))
        font = QtGui.QFont()
        self.y_axisPositionLbl.setFont(font)
        self.y_axisPositionLbl.setWordWrap(False)
        self.y_axisPositionLbl.setObjectName(_fromUtf8("y_axisPositionLbl"))
        self.pointSizeCBoxChangeAll = QtGui.QComboBox(plotNameForm)
        self.pointSizeCBoxChangeAll.setGeometry(QtCore.QRect(640, 460, 50, 20))
        self.pointSizeCBoxChangeAll.setObjectName(_fromUtf8("pointSizeCBoxChangeAll"))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointSizeCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll = QtGui.QComboBox(plotNameForm)
        self.pointsCBoxChangeAll.setGeometry(QtCore.QRect(510, 460, 120, 20))
        self.pointsCBoxChangeAll.setObjectName(_fromUtf8("pointsCBoxChangeAll"))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.pointsCBoxChangeAll.addItem(_fromUtf8(""))
        self.cancelBtn = QtGui.QPushButton(plotNameForm)
        self.cancelBtn.setGeometry(QtCore.QRect(540, 560, 87, 30))
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.legendCBox = QtGui.QComboBox(plotNameForm)
        self.legendCBox.setGeometry(QtCore.QRect(280, 510, 140, 20))
        self.legendCBox.setObjectName(_fromUtf8("legendCBox"))
        self.legendCBox.addItem(_fromUtf8(""))
        self.legendCBox.addItem(_fromUtf8(""))
        self.legendCBox.addItem(_fromUtf8(""))
        self.LegendPositioningLbl = QtGui.QLabel(plotNameForm)
        self.LegendPositioningLbl.setGeometry(QtCore.QRect(150, 510, 120, 20))
        font = QtGui.QFont()
        self.LegendPositioningLbl.setFont(font)
        self.LegendPositioningLbl.setWordWrap(False)
        self.LegendPositioningLbl.setObjectName(_fromUtf8("LegendPositioningLbl"))
        self.x_axisEdit = QtGui.QLineEdit(plotNameForm)
        self.x_axisEdit.setEnabled(False)
        self.x_axisEdit.setGeometry(QtCore.QRect(540, 510, 70, 23))
        font = QtGui.QFont()
        self.x_axisEdit.setFont(font)
        self.x_axisEdit.setObjectName(_fromUtf8("x_axisEdit"))
        self.y_axisEdit = QtGui.QLineEdit(plotNameForm)
        self.y_axisEdit.setEnabled(False)
        self.y_axisEdit.setGeometry(QtCore.QRect(720, 510, 70, 23))
        font = QtGui.QFont()
        self.y_axisEdit.setFont(font)
        self.y_axisEdit.setObjectName(_fromUtf8("y_axisEdit"))
        self.x_axisPositionLbl = QtGui.QLabel(plotNameForm)
        self.x_axisPositionLbl.setEnabled(False)
        self.x_axisPositionLbl.setGeometry(QtCore.QRect(450, 510, 90, 20))
        font = QtGui.QFont()
        self.x_axisPositionLbl.setFont(font)
        self.x_axisPositionLbl.setWordWrap(False)
        self.x_axisPositionLbl.setObjectName(_fromUtf8("x_axisPositionLbl"))
        self.doneBtn = QtGui.QPushButton(plotNameForm)
        self.doneBtn.setGeometry(QtCore.QRect(190, 560, 87, 30))
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.saveSettingsLbl = QtGui.QLabel(plotNameForm)
        self.saveSettingsLbl.setEnabled(True)
        self.saveSettingsLbl.setGeometry(QtCore.QRect(280, 440, 137, 20))
        font = QtGui.QFont()
        self.saveSettingsLbl.setFont(font)
        self.saveSettingsLbl.setWordWrap(False)
        self.saveSettingsLbl.setObjectName(_fromUtf8("saveSettingsLbl"))
        self.SaveTimeButton = QtGui.QPushButton(plotNameForm)
        self.SaveTimeButton.setGeometry(QtCore.QRect(40, 460, 71, 31))
        self.SaveTimeButton.setObjectName(_fromUtf8("SaveTimeButton"))
        self.saveSettingsBtn = QtGui.QPushButton(plotNameForm)
        self.saveSettingsBtn.setGeometry(QtCore.QRect(290, 460, 50, 30))
        self.saveSettingsBtn.setObjectName(_fromUtf8("saveSettingsBtn"))
        self.restoreSettingsBtn = QtGui.QPushButton(plotNameForm)
        self.restoreSettingsBtn.setGeometry(QtCore.QRect(350, 460, 60, 31))
        self.restoreSettingsBtn.setObjectName(_fromUtf8("restoreSettingsBtn"))

        self.retranslateUi(plotNameForm)
        QtCore.QObject.connect(self.doneBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), plotNameForm.doneBtn_pressed)
        QtCore.QObject.connect(self.legendCBox, QtCore.SIGNAL(_fromUtf8("activated(int)")), plotNameForm.LegendPosition_selected)
        QtCore.QObject.connect(self.SaveTimeButton, QtCore.SIGNAL(_fromUtf8("pressed()")), plotNameForm.SaveTimeButton_pressed)
        QtCore.QObject.connect(self.pointsCBoxChangeAll, QtCore.SIGNAL(_fromUtf8("activated(int)")), plotNameForm.pointsCBoxChangeAll_activated)
        QtCore.QObject.connect(self.pointSizeCBoxChangeAll, QtCore.SIGNAL(_fromUtf8("activated(int)")), plotNameForm.pointSizeCBoxChangeAll_activated)
        QtCore.QObject.connect(self.lineWidthCBoxChangeAll, QtCore.SIGNAL(_fromUtf8("activated(int)")), plotNameForm.lineWidthCBoxChangeAll_activated)
        QtCore.QObject.connect(self.lineColorCBoxChangeAll, QtCore.SIGNAL(_fromUtf8("activated(int)")), plotNameForm.lineColorCBoxChangeAll_activated)
        QtCore.QObject.connect(self.saveSettingsBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), plotNameForm.saveSettingsBtn_pressed)
        QtCore.QObject.connect(self.restoreSettingsBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), plotNameForm.restoreSettingsBtn_pressed)
        QtCore.QMetaObject.connectSlotsByName(plotNameForm)
        plotNameForm.setTabOrder(self.file1Edit, self.file2Edit)
        plotNameForm.setTabOrder(self.file2Edit, self.file3Edit)
        plotNameForm.setTabOrder(self.file3Edit, self.file4Edit)
        plotNameForm.setTabOrder(self.file4Edit, self.file5Edit)
        plotNameForm.setTabOrder(self.file5Edit, self.file6Edit)
        plotNameForm.setTabOrder(self.file6Edit, self.file7Edit)
        plotNameForm.setTabOrder(self.file7Edit, self.doneBtn)
        plotNameForm.setTabOrder(self.doneBtn, self.cancelBtn)

    def retranslateUi(self, plotNameForm):
        plotNameForm.setWindowTitle(_translate("plotNameForm", "Plot Naming", None))
        self.file1Lbl.setText(_translate("plotNameForm", "file1", None))
        self.PlotLegendLbl.setText(_translate("plotNameForm", "Plot Legend", None))
        self.lineColorCBox1.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox1.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox1.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox1.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox1.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox1.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox1.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox1.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox1.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.file7Lbl.setText(_translate("plotNameForm", "file7", None))
        self.textLabel1.setText(_translate("plotNameForm", "Plot Order", None))
        self.LineWidthLbl_2_2.setText(_translate("plotNameForm", "Line Color", None))
        self.file5Lbl.setText(_translate("plotNameForm", "file5", None))
        self.lineColorCBox6.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox6.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox6.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox6.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox6.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox6.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox6.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox6.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox6.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.lineColorCBox3.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox3.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox3.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox3.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox3.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox3.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox3.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox3.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox3.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.lineColorCBox2.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox2.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox2.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox2.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox2.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox2.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox2.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox2.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox2.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.PointSizeLbl.setText(_translate("plotNameForm", "<p align=\"center\">Point \n"
"Size</p>", None))
        self.lineColorCBox7.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox7.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox7.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox7.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox7.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox7.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox7.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox7.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox7.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.lineColorCBox5.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox5.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox5.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox5.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox5.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox5.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox5.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox5.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox5.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.file6Lbl.setText(_translate("plotNameForm", "file6", None))
        self.LineWidthLbl_2.setText(_translate("plotNameForm", "<p align=\"center\">Line \n"
"Width</p>", None))
        self.PointsLbl.setText(_translate("plotNameForm", "Point Type", None))
        self.lineColorCBox4.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox4.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox4.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox4.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox4.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox4.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox4.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox4.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox4.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.plotOrder6.setText(_translate("plotNameForm", "6", None))
        self.plotOrder7.setText(_translate("plotNameForm", "7", None))
        self.pointsCBox3.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox3.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox3.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox3.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox3.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox3.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox3.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox3.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox3.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox3.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox3.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox3.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.pointsCBox4.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox4.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox4.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox4.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox4.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox4.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox4.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox4.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox4.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox4.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox4.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox4.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.pointsCBox5.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox5.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox5.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox5.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox5.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox5.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox5.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox5.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox5.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox5.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox5.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox5.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.pointsCBox6.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox6.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox6.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox6.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox6.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox6.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox6.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox6.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox6.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox6.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox6.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox6.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.file8Lbl.setText(_translate("plotNameForm", "file8", None))
        self.file3Lbl.setText(_translate("plotNameForm", "file3", None))
        self.plotOrder1.setText(_translate("plotNameForm", "1", None))
        self.plotOrder2.setText(_translate("plotNameForm", "2", None))
        self.plotOrder3.setText(_translate("plotNameForm", "3", None))
        self.plotOrder4.setText(_translate("plotNameForm", "4", None))
        self.plotOrder5.setText(_translate("plotNameForm", "5", None))
        self.pointSizeCBox1.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox1.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox1.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox1.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox1.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox1.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox1.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox1.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox1.setItemText(8, _translate("plotNameForm", "3", None))
        self.pointSizeCBox2.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox2.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox2.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox2.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox2.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox2.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox2.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox2.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox2.setItemText(8, _translate("plotNameForm", "3", None))
        self.pointSizeCBox3.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox3.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox3.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox3.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox3.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox3.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox3.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox3.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox3.setItemText(8, _translate("plotNameForm", "3", None))
        self.pointSizeCBox4.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox4.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox4.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox4.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox4.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox4.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox4.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox4.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox4.setItemText(8, _translate("plotNameForm", "3", None))
        self.pointSizeCBox5.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox5.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox5.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox5.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox5.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox5.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox5.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox5.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox5.setItemText(8, _translate("plotNameForm", "3", None))
        self.pointSizeCBox6.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox6.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox6.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox6.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox6.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox6.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox6.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox6.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox6.setItemText(8, _translate("plotNameForm", "3", None))
        self.pointSizeCBox7.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox7.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox7.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox7.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox7.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox7.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox7.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox7.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox7.setItemText(8, _translate("plotNameForm", "3", None))
        self.lineWidthCBox1.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox1.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox1.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox1.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox1.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox1.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineWidthCBox2.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox2.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox2.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox2.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox2.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox2.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineWidthCBox3.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox3.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox3.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox3.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox3.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox3.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineWidthCBox4.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox4.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox4.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox4.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox4.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox4.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineWidthCBox5.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox5.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox5.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox5.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox5.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox5.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineWidthCBox6.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox6.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox6.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox6.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox6.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox6.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineWidthCBox7.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox7.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox7.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox7.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox7.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox7.setItemText(5, _translate("plotNameForm", "6", None))
        self.file4Lbl.setText(_translate("plotNameForm", "file4", None))
        self.file2Lbl.setText(_translate("plotNameForm", "file2", None))
        self.pointsCBox7.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox7.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox7.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox7.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox7.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox7.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox7.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox7.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox7.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox7.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox7.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox7.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.plotOrder8.setText(_translate("plotNameForm", "8", None))
        self.pointsCBox8.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox8.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox8.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox8.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox8.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox8.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox8.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox8.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox8.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox8.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox8.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox8.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.pointSizeCBox8.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBox8.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBox8.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBox8.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBox8.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBox8.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBox8.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBox8.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBox8.setItemText(8, _translate("plotNameForm", "3", None))
        self.lineWidthCBox8.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBox8.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBox8.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBox8.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBox8.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBox8.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineColorCBox8.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBox8.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBox8.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBox8.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBox8.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBox8.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBox8.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBox8.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBox8.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.pointsCBox1.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox1.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox1.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox1.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox1.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox1.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox1.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox1.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox1.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox1.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox1.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox1.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.pointsCBox2.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBox2.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBox2.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBox2.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBox2.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBox2.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBox2.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBox2.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBox2.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBox2.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBox2.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBox2.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.lineWidthCBoxChangeAll.setItemText(0, _translate("plotNameForm", "1", None))
        self.lineWidthCBoxChangeAll.setItemText(1, _translate("plotNameForm", "2", None))
        self.lineWidthCBoxChangeAll.setItemText(2, _translate("plotNameForm", "3", None))
        self.lineWidthCBoxChangeAll.setItemText(3, _translate("plotNameForm", "4", None))
        self.lineWidthCBoxChangeAll.setItemText(4, _translate("plotNameForm", "5", None))
        self.lineWidthCBoxChangeAll.setItemText(5, _translate("plotNameForm", "6", None))
        self.lineColorCBoxChangeAll.setItemText(0, _translate("plotNameForm", "black", None))
        self.lineColorCBoxChangeAll.setItemText(1, _translate("plotNameForm", "red", None))
        self.lineColorCBoxChangeAll.setItemText(2, _translate("plotNameForm", "green", None))
        self.lineColorCBoxChangeAll.setItemText(3, _translate("plotNameForm", "blue", None))
        self.lineColorCBoxChangeAll.setItemText(4, _translate("plotNameForm", "purple", None))
        self.lineColorCBoxChangeAll.setItemText(5, _translate("plotNameForm", "aqua", None))
        self.lineColorCBoxChangeAll.setItemText(6, _translate("plotNameForm", "brown", None))
        self.lineColorCBoxChangeAll.setItemText(7, _translate("plotNameForm", "orange", None))
        self.lineColorCBoxChangeAll.setItemText(8, _translate("plotNameForm", "Light Brown", None))
        self.y_axisPositionLbl.setText(_translate("plotNameForm", "y-axis Position:", None))
        self.pointSizeCBoxChangeAll.setItemText(0, _translate("plotNameForm", "0", None))
        self.pointSizeCBoxChangeAll.setItemText(1, _translate("plotNameForm", "1", None))
        self.pointSizeCBoxChangeAll.setItemText(2, _translate("plotNameForm", "1.25", None))
        self.pointSizeCBoxChangeAll.setItemText(3, _translate("plotNameForm", "1.5", None))
        self.pointSizeCBoxChangeAll.setItemText(4, _translate("plotNameForm", "1.75", None))
        self.pointSizeCBoxChangeAll.setItemText(5, _translate("plotNameForm", "2", None))
        self.pointSizeCBoxChangeAll.setItemText(6, _translate("plotNameForm", "2.25", None))
        self.pointSizeCBoxChangeAll.setItemText(7, _translate("plotNameForm", "2.5", None))
        self.pointSizeCBoxChangeAll.setItemText(8, _translate("plotNameForm", "3", None))
        self.pointsCBoxChangeAll.setItemText(0, _translate("plotNameForm", "No Points", None))
        self.pointsCBoxChangeAll.setItemText(1, _translate("plotNameForm", "Plus", None))
        self.pointsCBoxChangeAll.setItemText(2, _translate("plotNameForm", "Multiply", None))
        self.pointsCBoxChangeAll.setItemText(3, _translate("plotNameForm", "Star", None))
        self.pointsCBoxChangeAll.setItemText(4, _translate("plotNameForm", "Dotted Square", None))
        self.pointsCBoxChangeAll.setItemText(5, _translate("plotNameForm", "Solid Square", None))
        self.pointsCBoxChangeAll.setItemText(6, _translate("plotNameForm", "Dotted Circle", None))
        self.pointsCBoxChangeAll.setItemText(7, _translate("plotNameForm", "Solid Circle", None))
        self.pointsCBoxChangeAll.setItemText(8, _translate("plotNameForm", "Dotted Triangle", None))
        self.pointsCBoxChangeAll.setItemText(9, _translate("plotNameForm", "Solid Trangle", None))
        self.pointsCBoxChangeAll.setItemText(10, _translate("plotNameForm", "UsD Dotted Tri.", None))
        self.pointsCBoxChangeAll.setItemText(11, _translate("plotNameForm", "UsD Solid Tri.", None))
        self.cancelBtn.setText(_translate("plotNameForm", "Cancel", None))
        self.legendCBox.setItemText(0, _translate("plotNameForm", "Default Position", None))
        self.legendCBox.setItemText(1, _translate("plotNameForm", "Customized Position", None))
        self.legendCBox.setItemText(2, _translate("plotNameForm", "Remove Legend", None))
        self.LegendPositioningLbl.setText(_translate("plotNameForm", "Plot Legend Position:", None))
        self.x_axisPositionLbl.setText(_translate("plotNameForm", "x-axis Position:", None))
        self.doneBtn.setText(_translate("plotNameForm", "Done", None))
        self.saveSettingsLbl.setText(_translate("plotNameForm", "Settings Management", None))
        self.SaveTimeButton.setText(_translate("plotNameForm", "Save Time", None))
        self.saveSettingsBtn.setText(_translate("plotNameForm", "Save", None))
        self.restoreSettingsBtn.setText(_translate("plotNameForm", "Restore", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    plotNameForm = QtGui.QWidget()
    ui = Ui_plotNameForm()
    ui.setupUi(plotNameForm)
    plotNameForm.show()
    sys.exit(app.exec_())

