# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'siminitform.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SimInitForm(object):
    def setupUi(self, SimInitForm):
        SimInitForm.setObjectName(_fromUtf8("SimInitForm"))
        SimInitForm.resize(1325, 887)
        self.simIdLbl = QtGui.QLabel(SimInitForm)
        self.simIdLbl.setGeometry(QtCore.QRect(20, 40, 90, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.simIdLbl.setFont(font)
        self.simIdLbl.setWordWrap(False)
        self.simIdLbl.setObjectName(_fromUtf8("simIdLbl"))
        self.usernameEdit = QtGui.QLineEdit(SimInitForm)
        self.usernameEdit.setGeometry(QtCore.QRect(120, 10, 200, 21))
        self.usernameEdit.setObjectName(_fromUtf8("usernameEdit"))
        self.passwordLbl = QtGui.QLabel(SimInitForm)
        self.passwordLbl.setGeometry(QtCore.QRect(340, 10, 70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.passwordLbl.setFont(font)
        self.passwordLbl.setWordWrap(False)
        self.passwordLbl.setObjectName(_fromUtf8("passwordLbl"))
        self.hostEdit = QtGui.QLineEdit(SimInitForm)
        self.hostEdit.setGeometry(QtCore.QRect(410, 40, 230, 23))
        self.hostEdit.setObjectName(_fromUtf8("hostEdit"))
        self.loginBtn = QtGui.QPushButton(SimInitForm)
        self.loginBtn.setGeometry(QtCore.QRect(650, 10, 70, 28))
        self.loginBtn.setObjectName(_fromUtf8("loginBtn"))
        self.logoutBtn = QtGui.QPushButton(SimInitForm)
        self.logoutBtn.setEnabled(False)
        self.logoutBtn.setGeometry(QtCore.QRect(730, 10, 90, 28))
        self.logoutBtn.setObjectName(_fromUtf8("logoutBtn"))
        self.passwordEdit = QtGui.QLineEdit(SimInitForm)
        self.passwordEdit.setGeometry(QtCore.QRect(410, 10, 230, 22))
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName(_fromUtf8("passwordEdit"))
        self.usernameLbl = QtGui.QLabel(SimInitForm)
        self.usernameLbl.setGeometry(QtCore.QRect(30, 10, 70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usernameLbl.setFont(font)
        self.usernameLbl.setWordWrap(False)
        self.usernameLbl.setObjectName(_fromUtf8("usernameLbl"))
        self.simIdEdit = QtGui.QLineEdit(SimInitForm)
        self.simIdEdit.setGeometry(QtCore.QRect(120, 40, 200, 21))
        self.simIdEdit.setObjectName(_fromUtf8("simIdEdit"))
        self.hostLbl = QtGui.QLabel(SimInitForm)
        self.hostLbl.setGeometry(QtCore.QRect(350, 40, 50, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hostLbl.setFont(font)
        self.hostLbl.setWordWrap(False)
        self.hostLbl.setObjectName(_fromUtf8("hostLbl"))
        self.FRateLbl = QtGui.QLabel(SimInitForm)
        self.FRateLbl.setEnabled(False)
        self.FRateLbl.setGeometry(QtCore.QRect(780, 290, 70, 20))
        font = QtGui.QFont()
        self.FRateLbl.setFont(font)
        self.FRateLbl.setWordWrap(False)
        self.FRateLbl.setObjectName(_fromUtf8("FRateLbl"))
        self.videoTraceFileLbl = QtGui.QLabel(SimInitForm)
        self.videoTraceFileLbl.setGeometry(QtCore.QRect(500, 390, 100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.videoTraceFileLbl.setFont(font)
        self.videoTraceFileLbl.setWordWrap(False)
        self.videoTraceFileLbl.setObjectName(_fromUtf8("videoTraceFileLbl"))
        self.changeTraceBtn = QtGui.QPushButton(SimInitForm)
        self.changeTraceBtn.setEnabled(False)
        self.changeTraceBtn.setGeometry(QtCore.QRect(760, 380, 90, 30))
        self.changeTraceBtn.setObjectName(_fromUtf8("changeTraceBtn"))
        self.videoTraceEdit = QtGui.QLineEdit(SimInitForm)
        self.videoTraceEdit.setEnabled(False)
        self.videoTraceEdit.setGeometry(QtCore.QRect(500, 410, 350, 22))
        self.videoTraceEdit.setReadOnly(True)
        self.videoTraceEdit.setObjectName(_fromUtf8("videoTraceEdit"))
        self.launchBtn = QtGui.QPushButton(SimInitForm)
        self.launchBtn.setEnabled(False)
        self.launchBtn.setGeometry(QtCore.QRect(50, 760, 86, 28))
        self.launchBtn.setObjectName(_fromUtf8("launchBtn"))
        self.cancelBtn = QtGui.QPushButton(SimInitForm)
        self.cancelBtn.setGeometry(QtCore.QRect(210, 760, 86, 28))
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.saveTimeButton = QtGui.QPushButton(SimInitForm)
        self.saveTimeButton.setGeometry(QtCore.QRect(790, 350, 40, 20))
        self.saveTimeButton.setText(_fromUtf8(""))
        self.saveTimeButton.setObjectName(_fromUtf8("saveTimeButton"))
        self.indexMaxIncreaseButton = QtGui.QPushButton(SimInitForm)
        self.indexMaxIncreaseButton.setGeometry(QtCore.QRect(450, 730, 30, 20))
        self.indexMaxIncreaseButton.setObjectName(_fromUtf8("indexMaxIncreaseButton"))
        self.indexMaxDecreaseButton = QtGui.QPushButton(SimInitForm)
        self.indexMaxDecreaseButton.setGeometry(QtCore.QRect(410, 730, 30, 20))
        self.indexMaxDecreaseButton.setObjectName(_fromUtf8("indexMaxDecreaseButton"))
        self.indexDecreaseButton = QtGui.QPushButton(SimInitForm)
        self.indexDecreaseButton.setGeometry(QtCore.QRect(350, 760, 30, 30))
        self.indexDecreaseButton.setObjectName(_fromUtf8("indexDecreaseButton"))
        self.queueIndexSlotEdit = QtGui.QLineEdit(SimInitForm)
        self.queueIndexSlotEdit.setGeometry(QtCore.QRect(390, 760, 30, 30))
        self.queueIndexSlotEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.queueIndexSlotEdit.setReadOnly(True)
        self.queueIndexSlotEdit.setObjectName(_fromUtf8("queueIndexSlotEdit"))
        self.frameRateEdit = QtGui.QLineEdit(SimInitForm)
        self.frameRateEdit.setEnabled(False)
        self.frameRateEdit.setGeometry(QtCore.QRect(790, 310, 40, 22))
        self.frameRateEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frameRateEdit.setObjectName(_fromUtf8("frameRateEdit"))
        self.indexIncreaseButton = QtGui.QPushButton(SimInitForm)
        self.indexIncreaseButton.setGeometry(QtCore.QRect(430, 760, 30, 30))
        self.indexIncreaseButton.setObjectName(_fromUtf8("indexIncreaseButton"))
        self.parallelSimsEdit = QtGui.QLineEdit(SimInitForm)
        self.parallelSimsEdit.setGeometry(QtCore.QRect(790, 780, 40, 23))
        self.parallelSimsEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.parallelSimsEdit.setObjectName(_fromUtf8("parallelSimsEdit"))
        self.parallelSimsLbl = QtGui.QLabel(SimInitForm)
        self.parallelSimsLbl.setGeometry(QtCore.QRect(700, 780, 80, 20))
        self.parallelSimsLbl.setWordWrap(False)
        self.parallelSimsLbl.setObjectName(_fromUtf8("parallelSimsLbl"))
        self.AuxLabel1 = QtGui.QLabel(SimInitForm)
        self.AuxLabel1.setEnabled(True)
        self.AuxLabel1.setGeometry(QtCore.QRect(50, 800, 340, 63))
        self.AuxLabel1.setWordWrap(False)
        self.AuxLabel1.setObjectName(_fromUtf8("AuxLabel1"))
        self.dbaGatedVideoBtn = QtGui.QRadioButton(SimInitForm)
        self.dbaGatedVideoBtn.setEnabled(False)
        self.dbaGatedVideoBtn.setGeometry(QtCore.QRect(730, 90, 70, 22))
        self.dbaGatedVideoBtn.setChecked(False)
        self.dbaGatedVideoBtn.setObjectName(_fromUtf8("dbaGatedVideoBtn"))
        self.buttonGroup_3 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.dbaGatedVideoBtn)
        self.dbaFixedVideoBtn = QtGui.QRadioButton(SimInitForm)
        self.dbaFixedVideoBtn.setEnabled(False)
        self.dbaFixedVideoBtn.setGeometry(QtCore.QRect(730, 110, 70, 22))
        self.dbaFixedVideoBtn.setObjectName(_fromUtf8("dbaFixedVideoBtn"))
        self.buttonGroup_3.addButton(self.dbaFixedVideoBtn)
        self.dbaLimitedVideoBtn = QtGui.QRadioButton(SimInitForm)
        self.dbaLimitedVideoBtn.setEnabled(False)
        self.dbaLimitedVideoBtn.setGeometry(QtCore.QRect(730, 130, 80, 22))
        self.dbaLimitedVideoBtn.setChecked(True)
        self.dbaLimitedVideoBtn.setObjectName(_fromUtf8("dbaLimitedVideoBtn"))
        self.buttonGroup_3.addButton(self.dbaLimitedVideoBtn)
        self.label = QtGui.QLabel(SimInitForm)
        self.label.setGeometry(QtCore.QRect(710, 72, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setObjectName(_fromUtf8("label"))
        self.dbaGatedBtn = QtGui.QRadioButton(SimInitForm)
        self.dbaGatedBtn.setGeometry(QtCore.QRect(590, 90, 80, 22))
        self.dbaGatedBtn.setObjectName(_fromUtf8("dbaGatedBtn"))
        self.buttonGroup_2 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.dbaGatedBtn)
        self.dbaFixedBtn = QtGui.QRadioButton(SimInitForm)
        self.dbaFixedBtn.setGeometry(QtCore.QRect(590, 110, 70, 22))
        self.dbaFixedBtn.setObjectName(_fromUtf8("dbaFixedBtn"))
        self.buttonGroup_2.addButton(self.dbaFixedBtn)
        self.dbaExcessBtn = QtGui.QRadioButton(SimInitForm)
        self.dbaExcessBtn.setGeometry(QtCore.QRect(590, 150, 90, 21))
        self.dbaExcessBtn.setObjectName(_fromUtf8("dbaExcessBtn"))
        self.buttonGroup_2.addButton(self.dbaExcessBtn)
        self.dbaLimitedBtn = QtGui.QRadioButton(SimInitForm)
        self.dbaLimitedBtn.setGeometry(QtCore.QRect(590, 130, 90, 22))
        self.dbaLimitedBtn.setChecked(True)
        self.dbaLimitedBtn.setObjectName(_fromUtf8("dbaLimitedBtn"))
        self.buttonGroup_2.addButton(self.dbaLimitedBtn)
        self.label_2 = QtGui.QLabel(SimInitForm)
        self.label_2.setGeometry(QtCore.QRect(570, 72, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lfjsptBtn = QtGui.QRadioButton(SimInitForm)
        self.lfjsptBtn.setGeometry(QtCore.QRect(30, 131, 80, 20))
        self.lfjsptBtn.setObjectName(_fromUtf8("lfjsptBtn"))
        self.buttonGroup = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.lfjsptBtn)
        self.lfjlnfBtn = QtGui.QRadioButton(SimInitForm)
        self.lfjlnfBtn.setGeometry(QtCore.QRect(30, 150, 80, 21))
        self.lfjlnfBtn.setObjectName(_fromUtf8("lfjlnfBtn"))
        self.buttonGroup.addButton(self.lfjlnfBtn)
        self.lpdBtn = QtGui.QRadioButton(SimInitForm)
        self.lpdBtn.setGeometry(QtCore.QRect(30, 190, 112, 23))
        self.lpdBtn.setObjectName(_fromUtf8("lpdBtn"))
        self.buttonGroup.addButton(self.lpdBtn)
        self.lfjBtn = QtGui.QRadioButton(SimInitForm)
        self.lfjBtn.setGeometry(QtCore.QRect(430, 190, 50, 21))
        self.lfjBtn.setObjectName(_fromUtf8("lfjBtn"))
        self.buttonGroup.addButton(self.lfjBtn)
        self.apsBtn = QtGui.QRadioButton(SimInitForm)
        self.apsBtn.setGeometry(QtCore.QRect(430, 210, 60, 21))
        self.apsBtn.setObjectName(_fromUtf8("apsBtn"))
        self.buttonGroup.addButton(self.apsBtn)
        self.jitEafBtn = QtGui.QRadioButton(SimInitForm)
        self.jitEafBtn.setGeometry(QtCore.QRect(300, 210, 121, 22))
        self.jitEafBtn.setObjectName(_fromUtf8("jitEafBtn"))
        self.buttonGroup.addButton(self.jitEafBtn)
        self.jitEaafBtn = QtGui.QRadioButton(SimInitForm)
        self.jitEaafBtn.setGeometry(QtCore.QRect(300, 230, 121, 22))
        self.jitEaafBtn.setObjectName(_fromUtf8("jitEaafBtn"))
        self.buttonGroup.addButton(self.jitEaafBtn)
        self.eaafBtn = QtGui.QRadioButton(SimInitForm)
        self.eaafBtn.setGeometry(QtCore.QRect(30, 230, 80, 21))
        self.eaafBtn.setObjectName(_fromUtf8("eaafBtn"))
        self.buttonGroup.addButton(self.eaafBtn)
        self.jitLpdBtn = QtGui.QRadioButton(SimInitForm)
        self.jitLpdBtn.setGeometry(QtCore.QRect(300, 190, 111, 22))
        self.jitLpdBtn.setObjectName(_fromUtf8("jitLpdBtn"))
        self.buttonGroup.addButton(self.jitLpdBtn)
        self.intvlLfjlptBtn = QtGui.QRadioButton(SimInitForm)
        self.intvlLfjlptBtn.setGeometry(QtCore.QRect(150, 110, 130, 20))
        self.intvlLfjlptBtn.setObjectName(_fromUtf8("intvlLfjlptBtn"))
        self.buttonGroup.addButton(self.intvlLfjlptBtn)
        self.spdLptBtn = QtGui.QRadioButton(SimInitForm)
        self.spdLptBtn.setGeometry(QtCore.QRect(30, 250, 100, 22))
        self.spdLptBtn.setObjectName(_fromUtf8("spdLptBtn"))
        self.buttonGroup.addButton(self.spdLptBtn)
        self.jitTestBtn = QtGui.QRadioButton(SimInitForm)
        self.jitTestBtn.setGeometry(QtCore.QRect(430, 130, 90, 21))
        self.jitTestBtn.setObjectName(_fromUtf8("jitTestBtn"))
        self.buttonGroup.addButton(self.jitTestBtn)
        self.nascBtn = QtGui.QRadioButton(SimInitForm)
        self.nascBtn.setGeometry(QtCore.QRect(430, 110, 60, 21))
        self.nascBtn.setObjectName(_fromUtf8("nascBtn"))
        self.buttonGroup.addButton(self.nascBtn)
        self.ipactpsfBtn = QtGui.QRadioButton(SimInitForm)
        self.ipactpsfBtn.setEnabled(False)
        self.ipactpsfBtn.setGeometry(QtCore.QRect(430, 250, 100, 21))
        self.ipactpsfBtn.setChecked(True)
        self.ipactpsfBtn.setObjectName(_fromUtf8("ipactpsfBtn"))
        self.buttonGroup.addButton(self.ipactpsfBtn)
        self.jitSpdBtn = QtGui.QRadioButton(SimInitForm)
        self.jitSpdBtn.setGeometry(QtCore.QRect(300, 170, 111, 22))
        self.jitSpdBtn.setObjectName(_fromUtf8("jitSpdBtn"))
        self.buttonGroup.addButton(self.jitSpdBtn)
        self.intvlLfjsptBtn = QtGui.QRadioButton(SimInitForm)
        self.intvlLfjsptBtn.setGeometry(QtCore.QRect(150, 130, 140, 20))
        self.intvlLfjsptBtn.setObjectName(_fromUtf8("intvlLfjsptBtn"))
        self.buttonGroup.addButton(self.intvlLfjsptBtn)
        self.jitLfjsptBtn = QtGui.QRadioButton(SimInitForm)
        self.jitLfjsptBtn.setGeometry(QtCore.QRect(300, 130, 112, 21))
        self.jitLfjsptBtn.setObjectName(_fromUtf8("jitLfjsptBtn"))
        self.buttonGroup.addButton(self.jitLfjsptBtn)
        self.eafBtn = QtGui.QRadioButton(SimInitForm)
        self.eafBtn.setGeometry(QtCore.QRect(30, 210, 70, 21))
        self.eafBtn.setObjectName(_fromUtf8("eafBtn"))
        self.buttonGroup.addButton(self.eafBtn)
        self.ipactBtn = QtGui.QRadioButton(SimInitForm)
        self.ipactBtn.setGeometry(QtCore.QRect(430, 150, 70, 21))
        self.ipactBtn.setObjectName(_fromUtf8("ipactBtn"))
        self.buttonGroup.addButton(self.ipactBtn)
        self.intvlEafBtn = QtGui.QRadioButton(SimInitForm)
        self.intvlEafBtn.setGeometry(QtCore.QRect(150, 210, 121, 22))
        self.intvlEafBtn.setObjectName(_fromUtf8("intvlEafBtn"))
        self.buttonGroup.addButton(self.intvlEafBtn)
        self.jitLfjlptBtn = QtGui.QRadioButton(SimInitForm)
        self.jitLfjlptBtn.setGeometry(QtCore.QRect(300, 110, 112, 21))
        self.jitLfjlptBtn.setObjectName(_fromUtf8("jitLfjlptBtn"))
        self.buttonGroup.addButton(self.jitLfjlptBtn)
        self.spdBtn = QtGui.QRadioButton(SimInitForm)
        self.spdBtn.setGeometry(QtCore.QRect(30, 170, 112, 23))
        self.spdBtn.setObjectName(_fromUtf8("spdBtn"))
        self.buttonGroup.addButton(self.spdBtn)
        self.leastAssignedBtn = QtGui.QRadioButton(SimInitForm)
        self.leastAssignedBtn.setGeometry(QtCore.QRect(430, 170, 120, 21))
        self.leastAssignedBtn.setObjectName(_fromUtf8("leastAssignedBtn"))
        self.buttonGroup.addButton(self.leastAssignedBtn)
        self.intvlEaafBtn = QtGui.QRadioButton(SimInitForm)
        self.intvlEaafBtn.setGeometry(QtCore.QRect(150, 230, 121, 22))
        self.intvlEaafBtn.setObjectName(_fromUtf8("intvlEaafBtn"))
        self.buttonGroup.addButton(self.intvlEaafBtn)
        self.intvlLfjlnfBtn = QtGui.QRadioButton(SimInitForm)
        self.intvlLfjlnfBtn.setGeometry(QtCore.QRect(150, 150, 130, 20))
        self.intvlLfjlnfBtn.setObjectName(_fromUtf8("intvlLfjlnfBtn"))
        self.buttonGroup.addButton(self.intvlLfjlnfBtn)
        self.jitLfjlnfBtn = QtGui.QRadioButton(SimInitForm)
        self.jitLfjlnfBtn.setGeometry(QtCore.QRect(300, 150, 112, 21))
        self.jitLfjlnfBtn.setObjectName(_fromUtf8("jitLfjlnfBtn"))
        self.buttonGroup.addButton(self.jitLfjlnfBtn)
        self.lfjlptBtn = QtGui.QRadioButton(SimInitForm)
        self.lfjlptBtn.setGeometry(QtCore.QRect(30, 110, 80, 21))
        self.lfjlptBtn.setObjectName(_fromUtf8("lfjlptBtn"))
        self.buttonGroup.addButton(self.lfjlptBtn)
        self.textLabel5_2 = QtGui.QLabel(SimInitForm)
        self.textLabel5_2.setGeometry(QtCore.QRect(440, 90, 40, 20))
        self.textLabel5_2.setWordWrap(False)
        self.textLabel5_2.setObjectName(_fromUtf8("textLabel5_2"))
        self.textLabel4_2 = QtGui.QLabel(SimInitForm)
        self.textLabel4_2.setGeometry(QtCore.QRect(310, 90, 70, 20))
        self.textLabel4_2.setWordWrap(False)
        self.textLabel4_2.setObjectName(_fromUtf8("textLabel4_2"))
        self.textLabel3_2 = QtGui.QLabel(SimInitForm)
        self.textLabel3_2.setGeometry(QtCore.QRect(160, 90, 100, 20))
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName(_fromUtf8("textLabel3_2"))
        self.textLabel2_2 = QtGui.QLabel(SimInitForm)
        self.textLabel2_2.setGeometry(QtCore.QRect(40, 90, 61, 20))
        self.textLabel2_2.setWordWrap(False)
        self.textLabel2_2.setObjectName(_fromUtf8("textLabel2_2"))
        self.label_3 = QtGui.QLabel(SimInitForm)
        self.label_3.setGeometry(QtCore.QRect(10, 72, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.timeShiftLbl_2 = QtGui.QLabel(SimInitForm)
        self.timeShiftLbl_2.setEnabled(False)
        self.timeShiftLbl_2.setGeometry(QtCore.QRect(620, 310, 101, 20))
        font = QtGui.QFont()
        self.timeShiftLbl_2.setFont(font)
        self.timeShiftLbl_2.setWordWrap(False)
        self.timeShiftLbl_2.setObjectName(_fromUtf8("timeShiftLbl_2"))
        self.timeShiftEdit = QtGui.QLineEdit(SimInitForm)
        self.timeShiftEdit.setEnabled(False)
        self.timeShiftEdit.setGeometry(QtCore.QRect(720, 310, 40, 22))
        self.timeShiftEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeShiftEdit.setObjectName(_fromUtf8("timeShiftEdit"))
        self.vsOnBtn = QtGui.QRadioButton(SimInitForm)
        self.vsOnBtn.setGeometry(QtCore.QRect(570, 310, 50, 22))
        self.vsOnBtn.setObjectName(_fromUtf8("vsOnBtn"))
        self.buttonGroup_4 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.vsOnBtn)
        self.vsOffBtn = QtGui.QRadioButton(SimInitForm)
        self.vsOffBtn.setGeometry(QtCore.QRect(510, 310, 50, 22))
        self.vsOffBtn.setChecked(True)
        self.vsOffBtn.setObjectName(_fromUtf8("vsOffBtn"))
        self.buttonGroup_4.addButton(self.vsOffBtn)
        self.label_4 = QtGui.QLabel(SimInitForm)
        self.label_4.setGeometry(QtCore.QRect(500, 292, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.PredTypeEdit = QtGui.QLineEdit(SimInitForm)
        self.PredTypeEdit.setEnabled(False)
        self.PredTypeEdit.setGeometry(QtCore.QRect(700, 360, 40, 22))
        self.PredTypeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PredTypeEdit.setObjectName(_fromUtf8("PredTypeEdit"))
        self.pvtOffBtn = QtGui.QRadioButton(SimInitForm)
        self.pvtOffBtn.setGeometry(QtCore.QRect(510, 360, 50, 22))
        self.pvtOffBtn.setChecked(True)
        self.pvtOffBtn.setObjectName(_fromUtf8("pvtOffBtn"))
        self.buttonGroup_5 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.pvtOffBtn)
        self.PredTypeLbl_2 = QtGui.QLabel(SimInitForm)
        self.PredTypeLbl_2.setEnabled(False)
        self.PredTypeLbl_2.setGeometry(QtCore.QRect(630, 360, 70, 20))
        font = QtGui.QFont()
        self.PredTypeLbl_2.setFont(font)
        self.PredTypeLbl_2.setWordWrap(False)
        self.PredTypeLbl_2.setObjectName(_fromUtf8("PredTypeLbl_2"))
        self.pvtOnBtn = QtGui.QRadioButton(SimInitForm)
        self.pvtOnBtn.setGeometry(QtCore.QRect(570, 360, 50, 22))
        self.pvtOnBtn.setObjectName(_fromUtf8("pvtOnBtn"))
        self.buttonGroup_5.addButton(self.pvtOnBtn)
        self.label_5 = QtGui.QLabel(SimInitForm)
        self.label_5.setGeometry(QtCore.QRect(500, 342, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLineWidth(1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(SimInitForm)
        self.label_6.setGeometry(QtCore.QRect(700, 452, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(SimInitForm)
        self.label_7.setGeometry(QtCore.QRect(700, 502, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLineWidth(1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(SimInitForm)
        self.label_8.setGeometry(QtCore.QRect(700, 572, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(SimInitForm)
        self.label_9.setGeometry(QtCore.QRect(700, 622, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(SimInitForm)
        self.label_10.setGeometry(QtCore.QRect(700, 672, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLineWidth(1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(SimInitForm)
        self.label_11.setGeometry(QtCore.QRect(700, 722, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLineWidth(1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.svOnBtn = QtGui.QRadioButton(SimInitForm)
        self.svOnBtn.setGeometry(QtCore.QRect(770, 740, 50, 22))
        self.svOnBtn.setObjectName(_fromUtf8("svOnBtn"))
        self.buttonGroup_6 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.svOnBtn)
        self.svOffBtn = QtGui.QRadioButton(SimInitForm)
        self.svOffBtn.setGeometry(QtCore.QRect(710, 740, 50, 22))
        self.svOffBtn.setChecked(True)
        self.svOffBtn.setObjectName(_fromUtf8("svOffBtn"))
        self.buttonGroup_6.addButton(self.svOffBtn)
        self.gtOnBtn = QtGui.QRadioButton(SimInitForm)
        self.gtOnBtn.setGeometry(QtCore.QRect(770, 690, 50, 20))
        self.gtOnBtn.setObjectName(_fromUtf8("gtOnBtn"))
        self.buttonGroup_7 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.gtOnBtn)
        self.gtOffBtn = QtGui.QRadioButton(SimInitForm)
        self.gtOffBtn.setGeometry(QtCore.QRect(710, 690, 50, 20))
        self.gtOffBtn.setObjectName(_fromUtf8("gtOffBtn"))
        self.buttonGroup_7.addButton(self.gtOffBtn)
        self.grtOnBtn = QtGui.QRadioButton(SimInitForm)
        self.grtOnBtn.setGeometry(QtCore.QRect(770, 640, 50, 22))
        self.grtOnBtn.setObjectName(_fromUtf8("grtOnBtn"))
        self.buttonGroup_8 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_8.setObjectName(_fromUtf8("buttonGroup_8"))
        self.buttonGroup_8.addButton(self.grtOnBtn)
        self.grtOffBtn = QtGui.QRadioButton(SimInitForm)
        self.grtOffBtn.setGeometry(QtCore.QRect(710, 640, 60, 22))
        self.grtOffBtn.setObjectName(_fromUtf8("grtOffBtn"))
        self.buttonGroup_8.addButton(self.grtOffBtn)
        self.ttOnBtn = QtGui.QRadioButton(SimInitForm)
        self.ttOnBtn.setGeometry(QtCore.QRect(770, 590, 50, 20))
        self.ttOnBtn.setObjectName(_fromUtf8("ttOnBtn"))
        self.ttOffBtn = QtGui.QRadioButton(SimInitForm)
        self.ttOffBtn.setGeometry(QtCore.QRect(710, 590, 50, 20))
        self.ttOffBtn.setObjectName(_fromUtf8("ttOffBtn"))
        self.ssBtn = QtGui.QRadioButton(SimInitForm)
        self.ssBtn.setGeometry(QtCore.QRect(710, 540, 100, 21))
        self.ssBtn.setObjectName(_fromUtf8("ssBtn"))
        self.buttonGroup_9 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_9.setObjectName(_fromUtf8("buttonGroup_9"))
        self.buttonGroup_9.addButton(self.ssBtn)
        self.pnBtn = QtGui.QRadioButton(SimInitForm)
        self.pnBtn.setGeometry(QtCore.QRect(710, 520, 80, 21))
        self.pnBtn.setChecked(True)
        self.pnBtn.setObjectName(_fromUtf8("pnBtn"))
        self.buttonGroup_9.addButton(self.pnBtn)
        self.vtOffBtn = QtGui.QRadioButton(SimInitForm)
        self.vtOffBtn.setGeometry(QtCore.QRect(710, 470, 50, 22))
        self.vtOffBtn.setChecked(True)
        self.vtOffBtn.setObjectName(_fromUtf8("vtOffBtn"))
        self.buttonGroup_10 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_10.setObjectName(_fromUtf8("buttonGroup_10"))
        self.buttonGroup_10.addButton(self.vtOffBtn)
        self.vtOnBtn = QtGui.QRadioButton(SimInitForm)
        self.vtOnBtn.setGeometry(QtCore.QRect(770, 470, 50, 22))
        self.vtOnBtn.setObjectName(_fromUtf8("vtOnBtn"))
        self.buttonGroup_10.addButton(self.vtOnBtn)
        self.maxGrantSizeLbl = QtGui.QLabel(SimInitForm)
        self.maxGrantSizeLbl.setGeometry(QtCore.QRect(590, 250, 130, 20))
        font = QtGui.QFont()
        self.maxGrantSizeLbl.setFont(font)
        self.maxGrantSizeLbl.setWordWrap(False)
        self.maxGrantSizeLbl.setObjectName(_fromUtf8("maxGrantSizeLbl"))
        self.maxGrantSizeEdit = QtGui.QLineEdit(SimInitForm)
        self.maxGrantSizeEdit.setGeometry(QtCore.QRect(730, 250, 90, 22))
        self.maxGrantSizeEdit.setObjectName(_fromUtf8("maxGrantSizeEdit"))
        self.fixedGrantSizeLbl = QtGui.QLabel(SimInitForm)
        self.fixedGrantSizeLbl.setGeometry(QtCore.QRect(590, 220, 130, 20))
        font = QtGui.QFont()
        self.fixedGrantSizeLbl.setFont(font)
        self.fixedGrantSizeLbl.setWordWrap(False)
        self.fixedGrantSizeLbl.setObjectName(_fromUtf8("fixedGrantSizeLbl"))
        self.fixedGrantSizeEdit = QtGui.QLineEdit(SimInitForm)
        self.fixedGrantSizeEdit.setGeometry(QtCore.QRect(730, 220, 90, 22))
        self.fixedGrantSizeEdit.setObjectName(_fromUtf8("fixedGrantSizeEdit"))
        self.label_12 = QtGui.QLabel(SimInitForm)
        self.label_12.setGeometry(QtCore.QRect(570, 192, 150, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.svDropStepThreshold = QtGui.QRadioButton(SimInitForm)
        self.svDropStepThreshold.setGeometry(QtCore.QRect(520, 800, 90, 22))
        self.svDropStepThreshold.setChecked(False)
        self.svDropStepThreshold.setObjectName(_fromUtf8("svDropStepThreshold"))
        self.buttonGroup_11 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_11.setObjectName(_fromUtf8("buttonGroup_11"))
        self.buttonGroup_11.addButton(self.svDropStepThreshold)
        self.svDropStep_NumMAValues = QtGui.QLineEdit(SimInitForm)
        self.svDropStep_NumMAValues.setEnabled(False)
        self.svDropStep_NumMAValues.setGeometry(QtCore.QRect(620, 804, 40, 21))
        self.svDropStep_NumMAValues.setAlignment(QtCore.Qt.AlignRight)
        self.svDropStep_NumMAValues.setObjectName(_fromUtf8("svDropStep_NumMAValues"))
        self.svDropStepMinBound = QtGui.QLineEdit(SimInitForm)
        self.svDropStepMinBound.setEnabled(False)
        self.svDropStepMinBound.setGeometry(QtCore.QRect(580, 826, 80, 21))
        self.svDropStepMinBound.setAlignment(QtCore.Qt.AlignRight)
        self.svDropStepMinBound.setObjectName(_fromUtf8("svDropStepMinBound"))
        self.svDropDynamic = QtGui.QRadioButton(SimInitForm)
        self.svDropDynamic.setGeometry(QtCore.QRect(520, 780, 90, 22))
        self.svDropDynamic.setChecked(False)
        self.svDropDynamic.setObjectName(_fromUtf8("svDropDynamic"))
        self.buttonGroup_11.addButton(self.svDropDynamic)
        self.svDropDynamic_2 = QtGui.QRadioButton(SimInitForm)
        self.svDropDynamic_2.setGeometry(QtCore.QRect(520, 780, 90, 22))
        self.svDropDynamic_2.setChecked(False)
        self.svDropDynamic_2.setObjectName(_fromUtf8("svDropDynamic_2"))
        self.buttonGroup_11.addButton(self.svDropDynamic_2)
        self.svDropNone = QtGui.QRadioButton(SimInitForm)
        self.svDropNone.setGeometry(QtCore.QRect(520, 740, 90, 22))
        self.svDropNone.setChecked(False)
        self.svDropNone.setObjectName(_fromUtf8("svDropNone"))
        self.buttonGroup_11.addButton(self.svDropNone)
        self.svDropThresholdEdit = QtGui.QLineEdit(SimInitForm)
        self.svDropThresholdEdit.setEnabled(False)
        self.svDropThresholdEdit.setGeometry(QtCore.QRect(620, 760, 40, 21))
        self.svDropThresholdEdit.setAlignment(QtCore.Qt.AlignRight)
        self.svDropThresholdEdit.setObjectName(_fromUtf8("svDropThresholdEdit"))
        self.svDropSensitivity = QtGui.QLineEdit(SimInitForm)
        self.svDropSensitivity.setEnabled(False)
        self.svDropSensitivity.setGeometry(QtCore.QRect(620, 782, 40, 21))
        self.svDropSensitivity.setAlignment(QtCore.Qt.AlignRight)
        self.svDropSensitivity.setObjectName(_fromUtf8("svDropSensitivity"))
        self.svDropMaxBoundLabel = QtGui.QLabel(SimInitForm)
        self.svDropMaxBoundLabel.setEnabled(False)
        self.svDropMaxBoundLabel.setGeometry(QtCore.QRect(504, 850, 71, 20))
        self.svDropMaxBoundLabel.setWordWrap(False)
        self.svDropMaxBoundLabel.setObjectName(_fromUtf8("svDropMaxBoundLabel"))
        self.svDropStepMaxBound = QtGui.QLineEdit(SimInitForm)
        self.svDropStepMaxBound.setEnabled(False)
        self.svDropStepMaxBound.setGeometry(QtCore.QRect(580, 849, 80, 21))
        self.svDropStepMaxBound.setAlignment(QtCore.Qt.AlignRight)
        self.svDropStepMaxBound.setObjectName(_fromUtf8("svDropStepMaxBound"))
        self.svDropMinBoundLabel = QtGui.QLabel(SimInitForm)
        self.svDropMinBoundLabel.setGeometry(QtCore.QRect(504, 827, 68, 20))
        self.svDropMinBoundLabel.setWordWrap(False)
        self.svDropMinBoundLabel.setObjectName(_fromUtf8("svDropMinBoundLabel"))
        self.svDropThreshold_2 = QtGui.QRadioButton(SimInitForm)
        self.svDropThreshold_2.setGeometry(QtCore.QRect(520, 760, 90, 22))
        self.svDropThreshold_2.setObjectName(_fromUtf8("svDropThreshold_2"))
        self.buttonGroup_11.addButton(self.svDropThreshold_2)
        self.svDropNone_2 = QtGui.QRadioButton(SimInitForm)
        self.svDropNone_2.setGeometry(QtCore.QRect(520, 740, 90, 22))
        self.svDropNone_2.setChecked(True)
        self.svDropNone_2.setObjectName(_fromUtf8("svDropNone_2"))
        self.buttonGroup_11.addButton(self.svDropNone_2)
        self.svDropThreshold = QtGui.QRadioButton(SimInitForm)
        self.svDropThreshold.setGeometry(QtCore.QRect(520, 760, 90, 22))
        self.svDropThreshold.setObjectName(_fromUtf8("svDropThreshold"))
        self.buttonGroup_11.addButton(self.svDropThreshold)
        self.label_13 = QtGui.QLabel(SimInitForm)
        self.label_13.setGeometry(QtCore.QRect(500, 722, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(SimInitForm)
        self.label_14.setGeometry(QtCore.QRect(270, 602, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLineWidth(1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.fpdOnBtn = QtGui.QRadioButton(SimInitForm)
        self.fpdOnBtn.setGeometry(QtCore.QRect(390, 620, 60, 22))
        self.fpdOnBtn.setObjectName(_fromUtf8("fpdOnBtn"))
        self.buttonGroup_12 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_12.setObjectName(_fromUtf8("buttonGroup_12"))
        self.buttonGroup_12.addButton(self.fpdOnBtn)
        self.fpdOffBtn = QtGui.QRadioButton(SimInitForm)
        self.fpdOffBtn.setGeometry(QtCore.QRect(300, 620, 60, 22))
        self.fpdOffBtn.setObjectName(_fromUtf8("fpdOffBtn"))
        self.buttonGroup_12.addButton(self.fpdOffBtn)
        self.label_15 = QtGui.QLabel(SimInitForm)
        self.label_15.setGeometry(QtCore.QRect(270, 432, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLineWidth(1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.fixedBtn = QtGui.QRadioButton(SimInitForm)
        self.fixedBtn.setGeometry(QtCore.QRect(290, 460, 100, 20))
        self.fixedBtn.setObjectName(_fromUtf8("fixedBtn"))
        self.buttonGroup_13 = QtGui.QButtonGroup(SimInitForm)
        self.buttonGroup_13.setObjectName(_fromUtf8("buttonGroup_13"))
        self.buttonGroup_13.addButton(self.fixedBtn)
        self.tunableBtn = QtGui.QRadioButton(SimInitForm)
        self.tunableBtn.setGeometry(QtCore.QRect(390, 460, 80, 20))
        self.tunableBtn.setObjectName(_fromUtf8("tunableBtn"))
        self.buttonGroup_13.addButton(self.tunableBtn)
        self.runsLbl = QtGui.QLabel(SimInitForm)
        self.runsLbl.setGeometry(QtCore.QRect(50, 440, 80, 20))
        self.runsLbl.setWordWrap(False)
        self.runsLbl.setObjectName(_fromUtf8("runsLbl"))
        self.fpdValueLbl = QtGui.QLabel(SimInitForm)
        self.fpdValueLbl.setGeometry(QtCore.QRect(270, 660, 150, 20))
        self.fpdValueLbl.setWordWrap(False)
        self.fpdValueLbl.setObjectName(_fromUtf8("fpdValueLbl"))
        self.maxPropDelayEdit = QtGui.QLineEdit(SimInitForm)
        self.maxPropDelayEdit.setGeometry(QtCore.QRect(400, 690, 80, 21))
        self.maxPropDelayEdit.setObjectName(_fromUtf8("maxPropDelayEdit"))
        self.linkSpdEdit = QtGui.QLineEdit(SimInitForm)
        self.linkSpdEdit.setGeometry(QtCore.QRect(150, 510, 100, 21))
        self.linkSpdEdit.setObjectName(_fromUtf8("linkSpdEdit"))
        self.grdTimeEdit = QtGui.QLineEdit(SimInitForm)
        self.grdTimeEdit.setGeometry(QtCore.QRect(150, 570, 100, 23))
        self.grdTimeEdit.setObjectName(_fromUtf8("grdTimeEdit"))
        self.fpdValueEdit = QtGui.QLineEdit(SimInitForm)
        self.fpdValueEdit.setGeometry(QtCore.QRect(400, 660, 80, 22))
        self.fpdValueEdit.setObjectName(_fromUtf8("fpdValueEdit"))
        self.numHvyONUEdit = QtGui.QLineEdit(SimInitForm)
        self.numHvyONUEdit.setGeometry(QtCore.QRect(150, 630, 70, 21))
        self.numHvyONUEdit.setObjectName(_fromUtf8("numHvyONUEdit"))
        self.numLhWdmONULbl = QtGui.QLabel(SimInitForm)
        self.numLhWdmONULbl.setGeometry(QtCore.QRect(270, 560, 150, 20))
        self.numLhWdmONULbl.setWordWrap(False)
        self.numLhWdmONULbl.setObjectName(_fromUtf8("numLhWdmONULbl"))
        self.heavyLoadLbl = QtGui.QLabel(SimInitForm)
        self.heavyLoadLbl.setGeometry(QtCore.QRect(50, 660, 100, 20))
        self.heavyLoadLbl.setWordWrap(False)
        self.heavyLoadLbl.setObjectName(_fromUtf8("heavyLoadLbl"))
        self.numWdmONUEdit = QtGui.QLineEdit(SimInitForm)
        self.numWdmONUEdit.setGeometry(QtCore.QRect(410, 500, 70, 21))
        self.numWdmONUEdit.setObjectName(_fromUtf8("numWdmONUEdit"))
        self.linkSpdLbl = QtGui.QLabel(SimInitForm)
        self.linkSpdLbl.setGeometry(QtCore.QRect(50, 510, 80, 20))
        self.linkSpdLbl.setWordWrap(False)
        self.linkSpdLbl.setObjectName(_fromUtf8("linkSpdLbl"))
        self.numUhWdmONULbl = QtGui.QLabel(SimInitForm)
        self.numUhWdmONULbl.setGeometry(QtCore.QRect(270, 530, 150, 20))
        self.numUhWdmONULbl.setWordWrap(False)
        self.numUhWdmONULbl.setObjectName(_fromUtf8("numUhWdmONULbl"))
        self.numHvyONULbl = QtGui.QLabel(SimInitForm)
        self.numHvyONULbl.setGeometry(QtCore.QRect(20, 630, 130, 20))
        self.numHvyONULbl.setWordWrap(False)
        self.numHvyONULbl.setObjectName(_fromUtf8("numHvyONULbl"))
        self.numWdmONULbl = QtGui.QLabel(SimInitForm)
        self.numWdmONULbl.setGeometry(QtCore.QRect(270, 500, 120, 20))
        self.numWdmONULbl.setWordWrap(False)
        self.numWdmONULbl.setObjectName(_fromUtf8("numWdmONULbl"))
        self.simTimeEdit = QtGui.QLineEdit(SimInitForm)
        self.simTimeEdit.setGeometry(QtCore.QRect(150, 470, 100, 23))
        self.simTimeEdit.setObjectName(_fromUtf8("simTimeEdit"))
        self.numONUEdit = QtGui.QLineEdit(SimInitForm)
        self.numONUEdit.setGeometry(QtCore.QRect(150, 600, 70, 21))
        self.numONUEdit.setObjectName(_fromUtf8("numONUEdit"))
        self.numUhWdmONUEdit = QtGui.QLineEdit(SimInitForm)
        self.numUhWdmONUEdit.setGeometry(QtCore.QRect(410, 530, 70, 22))
        self.numUhWdmONUEdit.setObjectName(_fromUtf8("numUhWdmONUEdit"))
        self.grdTimeLbl = QtGui.QLabel(SimInitForm)
        self.grdTimeLbl.setGeometry(QtCore.QRect(50, 570, 80, 20))
        self.grdTimeLbl.setWordWrap(False)
        self.grdTimeLbl.setObjectName(_fromUtf8("grdTimeLbl"))
        self.numLhWdmONUEdit = QtGui.QLineEdit(SimInitForm)
        self.numLhWdmONUEdit.setGeometry(QtCore.QRect(410, 560, 70, 22))
        self.numLhWdmONUEdit.setObjectName(_fromUtf8("numLhWdmONUEdit"))
        self.heavyLoadEdit = QtGui.QLineEdit(SimInitForm)
        self.heavyLoadEdit.setGeometry(QtCore.QRect(150, 660, 70, 21))
        self.heavyLoadEdit.setObjectName(_fromUtf8("heavyLoadEdit"))
        self.runsEdit = QtGui.QLineEdit(SimInitForm)
        self.runsEdit.setGeometry(QtCore.QRect(150, 440, 100, 25))
        self.runsEdit.setObjectName(_fromUtf8("runsEdit"))
        self.simTimeLbl = QtGui.QLabel(SimInitForm)
        self.simTimeLbl.setGeometry(QtCore.QRect(60, 470, 70, 20))
        self.simTimeLbl.setWordWrap(False)
        self.simTimeLbl.setObjectName(_fromUtf8("simTimeLbl"))
        self.numONULbl = QtGui.QLabel(SimInitForm)
        self.numONULbl.setGeometry(QtCore.QRect(60, 600, 63, 20))
        self.numONULbl.setWordWrap(False)
        self.numONULbl.setObjectName(_fromUtf8("numONULbl"))
        self.maxPropDelayLbl = QtGui.QLabel(SimInitForm)
        self.maxPropDelayLbl.setGeometry(QtCore.QRect(270, 690, 140, 20))
        self.maxPropDelayLbl.setWordWrap(False)
        self.maxPropDelayLbl.setObjectName(_fromUtf8("maxPropDelayLbl"))
        self.tuningTimeEdit = QtGui.QLineEdit(SimInitForm)
        self.tuningTimeEdit.setGeometry(QtCore.QRect(150, 540, 100, 23))
        self.tuningTimeEdit.setObjectName(_fromUtf8("tuningTimeEdit"))
        self.tuningTimeLbl = QtGui.QLabel(SimInitForm)
        self.tuningTimeLbl.setGeometry(QtCore.QRect(50, 540, 82, 20))
        self.tuningTimeLbl.setWordWrap(False)
        self.tuningTimeLbl.setObjectName(_fromUtf8("tuningTimeLbl"))
        self.label_16 = QtGui.QLabel(SimInitForm)
        self.label_16.setGeometry(QtCore.QRect(10, 412, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLineWidth(1)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.numStrmsEdit = QtGui.QLineEdit(SimInitForm)
        self.numStrmsEdit.setGeometry(QtCore.QRect(610, 500, 50, 22))
        self.numStrmsEdit.setObjectName(_fromUtf8("numStrmsEdit"))
        self.numStrmsLbl = QtGui.QLabel(SimInitForm)
        self.numStrmsLbl.setGeometry(QtCore.QRect(510, 500, 94, 20))
        self.numStrmsLbl.setWordWrap(False)
        self.numStrmsLbl.setObjectName(_fromUtf8("numStrmsLbl"))
        self.hurstParamEdit = QtGui.QLineEdit(SimInitForm)
        self.hurstParamEdit.setGeometry(QtCore.QRect(610, 470, 50, 22))
        self.hurstParamEdit.setObjectName(_fromUtf8("hurstParamEdit"))
        self.hurstParamLbl = QtGui.QLabel(SimInitForm)
        self.hurstParamLbl.setGeometry(QtCore.QRect(510, 470, 93, 20))
        self.hurstParamLbl.setWordWrap(False)
        self.hurstParamLbl.setObjectName(_fromUtf8("hurstParamLbl"))
        self.label_17 = QtGui.QLabel(SimInitForm)
        self.label_17.setGeometry(QtCore.QRect(500, 452, 150, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLineWidth(1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.loadIncrEdit = QtGui.QLineEdit(SimInitForm)
        self.loadIncrEdit.setGeometry(QtCore.QRect(600, 610, 60, 22))
        self.loadIncrEdit.setObjectName(_fromUtf8("loadIncrEdit"))
        self.endLoadLbl = QtGui.QLabel(SimInitForm)
        self.endLoadLbl.setGeometry(QtCore.QRect(510, 580, 70, 20))
        self.endLoadLbl.setWordWrap(False)
        self.endLoadLbl.setObjectName(_fromUtf8("endLoadLbl"))
        self.loadIncrLbl = QtGui.QLabel(SimInitForm)
        self.loadIncrLbl.setGeometry(QtCore.QRect(510, 610, 80, 20))
        self.loadIncrLbl.setWordWrap(False)
        self.loadIncrLbl.setObjectName(_fromUtf8("loadIncrLbl"))
        self.endLoadEdit = QtGui.QLineEdit(SimInitForm)
        self.endLoadEdit.setGeometry(QtCore.QRect(600, 580, 60, 22))
        self.endLoadEdit.setObjectName(_fromUtf8("endLoadEdit"))
        self.startLoadEdit = QtGui.QLineEdit(SimInitForm)
        self.startLoadEdit.setGeometry(QtCore.QRect(600, 550, 60, 22))
        self.startLoadEdit.setObjectName(_fromUtf8("startLoadEdit"))
        self.startLoadLbl = QtGui.QLabel(SimInitForm)
        self.startLoadLbl.setGeometry(QtCore.QRect(510, 550, 80, 20))
        self.startLoadLbl.setWordWrap(False)
        self.startLoadLbl.setObjectName(_fromUtf8("startLoadLbl"))
        self.label_18 = QtGui.QLabel(SimInitForm)
        self.label_18.setGeometry(QtCore.QRect(500, 532, 130, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setLineWidth(1)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.endLambdaEdit = QtGui.QLineEdit(SimInitForm)
        self.endLambdaEdit.setGeometry(QtCore.QRect(620, 690, 40, 21))
        self.endLambdaEdit.setObjectName(_fromUtf8("endLambdaEdit"))
        self.startLambdaLbl = QtGui.QLabel(SimInitForm)
        self.startLambdaLbl.setGeometry(QtCore.QRect(510, 660, 120, 20))
        self.startLambdaLbl.setWordWrap(False)
        self.startLambdaLbl.setObjectName(_fromUtf8("startLambdaLbl"))
        self.startLambdaEdit = QtGui.QLineEdit(SimInitForm)
        self.startLambdaEdit.setGeometry(QtCore.QRect(620, 660, 40, 21))
        self.startLambdaEdit.setObjectName(_fromUtf8("startLambdaEdit"))
        self.endLambdaLbl = QtGui.QLabel(SimInitForm)
        self.endLambdaLbl.setGeometry(QtCore.QRect(510, 690, 110, 20))
        self.endLambdaLbl.setWordWrap(False)
        self.endLambdaLbl.setObjectName(_fromUtf8("endLambdaLbl"))
        self.label_19 = QtGui.QLabel(SimInitForm)
        self.label_19.setGeometry(QtCore.QRect(500, 642, 150, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLineWidth(1)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.schedulerSlotSizeLbl = QtGui.QLabel(SimInitForm)
        self.schedulerSlotSizeLbl.setGeometry(QtCore.QRect(280, 380, 180, 20))
        self.schedulerSlotSizeLbl.setWordWrap(False)
        self.schedulerSlotSizeLbl.setObjectName(_fromUtf8("schedulerSlotSizeLbl"))
        self.starveThreshLbl = QtGui.QLabel(SimInitForm)
        self.starveThreshLbl.setGeometry(QtCore.QRect(20, 320, 130, 20))
        font = QtGui.QFont()
        self.starveThreshLbl.setFont(font)
        self.starveThreshLbl.setWordWrap(False)
        self.starveThreshLbl.setObjectName(_fromUtf8("starveThreshLbl"))
        self.acwEdit = QtGui.QLineEdit(SimInitForm)
        self.acwEdit.setGeometry(QtCore.QRect(190, 350, 80, 24))
        self.acwEdit.setObjectName(_fromUtf8("acwEdit"))
        self.starveThreshEdit = QtGui.QLineEdit(SimInitForm)
        self.starveThreshEdit.setGeometry(QtCore.QRect(190, 320, 80, 24))
        self.starveThreshEdit.setObjectName(_fromUtf8("starveThreshEdit"))
        self.schedulerNumSlotLbl = QtGui.QLabel(SimInitForm)
        self.schedulerNumSlotLbl.setGeometry(QtCore.QRect(280, 350, 180, 20))
        font = QtGui.QFont()
        self.schedulerNumSlotLbl.setFont(font)
        self.schedulerNumSlotLbl.setWordWrap(False)
        self.schedulerNumSlotLbl.setObjectName(_fromUtf8("schedulerNumSlotLbl"))
        self.npoEdit = QtGui.QLineEdit(SimInitForm)
        self.npoEdit.setGeometry(QtCore.QRect(190, 380, 80, 24))
        self.npoEdit.setObjectName(_fromUtf8("npoEdit"))
        self.schedulerMaxWinChkBox = QtGui.QCheckBox(SimInitForm)
        self.schedulerMaxWinChkBox.setGeometry(QtCore.QRect(290, 320, 180, 21))
        font = QtGui.QFont()
        self.schedulerMaxWinChkBox.setFont(font)
        self.schedulerMaxWinChkBox.setObjectName(_fromUtf8("schedulerMaxWinChkBox"))
        self.acwLbl = QtGui.QLabel(SimInitForm)
        self.acwLbl.setGeometry(QtCore.QRect(20, 350, 150, 20))
        font = QtGui.QFont()
        self.acwLbl.setFont(font)
        self.acwLbl.setWordWrap(False)
        self.acwLbl.setObjectName(_fromUtf8("acwLbl"))
        self.npoLbl = QtGui.QLabel(SimInitForm)
        self.npoLbl.setGeometry(QtCore.QRect(20, 380, 170, 20))
        font = QtGui.QFont()
        self.npoLbl.setFont(font)
        self.npoLbl.setWordWrap(False)
        self.npoLbl.setObjectName(_fromUtf8("npoLbl"))
        self.schedulerNumSlotEdit = QtGui.QLineEdit(SimInitForm)
        self.schedulerNumSlotEdit.setGeometry(QtCore.QRect(450, 350, 30, 23))
        self.schedulerNumSlotEdit.setObjectName(_fromUtf8("schedulerNumSlotEdit"))
        self.schedulerSlotSizeEdit = QtGui.QLineEdit(SimInitForm)
        self.schedulerSlotSizeEdit.setGeometry(QtCore.QRect(450, 380, 30, 23))
        self.schedulerSlotSizeEdit.setObjectName(_fromUtf8("schedulerSlotSizeEdit"))
        self.label_20 = QtGui.QLabel(SimInitForm)
        self.label_20.setGeometry(QtCore.QRect(10, 292, 190, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setLineWidth(1)
        self.label_20.setObjectName(_fromUtf8("label_20"))

        self.retranslateUi(SimInitForm)
        QtCore.QObject.connect(self.cancelBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.cancelBtn_pressed)
        QtCore.QObject.connect(self.launchBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.launchBtn_pressed)
        QtCore.QObject.connect(self.loginBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.loginBtn_pressed)
        QtCore.QObject.connect(self.logoutBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.logoutBtn_pressed)
        QtCore.QObject.connect(self.changeTraceBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.changeTraceBtn_pressed)
        QtCore.QObject.connect(self.indexMaxIncreaseButton, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.indexMaxIncreaseButton_pressed)
        QtCore.QObject.connect(self.indexMaxDecreaseButton, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.indexMaxDecreaseButton_pressed)
        QtCore.QObject.connect(self.indexIncreaseButton, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.indexIncreaseButton_pressed)
        QtCore.QObject.connect(self.indexDecreaseButton, QtCore.SIGNAL(_fromUtf8("pressed()")), SimInitForm.indexDecreaseButton_pressed)
        QtCore.QMetaObject.connectSlotsByName(SimInitForm)
        SimInitForm.setTabOrder(self.passwordEdit, self.loginBtn)
        SimInitForm.setTabOrder(self.loginBtn, self.simIdEdit)
        SimInitForm.setTabOrder(self.simIdEdit, self.hostEdit)
        SimInitForm.setTabOrder(self.hostEdit, self.launchBtn)
        SimInitForm.setTabOrder(self.launchBtn, self.cancelBtn)
        SimInitForm.setTabOrder(self.cancelBtn, self.usernameEdit)
        SimInitForm.setTabOrder(self.usernameEdit, self.logoutBtn)

    def retranslateUi(self, SimInitForm):
        SimInitForm.setWindowTitle(_translate("SimInitForm", "Simulation Initialization", None))
        self.simIdLbl.setText(_translate("SimInitForm", "Simulation ID", None))
        self.passwordLbl.setText(_translate("SimInitForm", "Password", None))
        self.loginBtn.setText(_translate("SimInitForm", "Login", None))
        self.logoutBtn.setText(_translate("SimInitForm", "Logout", None))
        self.usernameLbl.setText(_translate("SimInitForm", "Username", None))
        self.hostLbl.setText(_translate("SimInitForm", "HOST", None))
        self.FRateLbl.setText(_translate("SimInitForm", "Frame Rate", None))
        self.videoTraceFileLbl.setText(_translate("SimInitForm", "Video Trace File", None))
        self.changeTraceBtn.setText(_translate("SimInitForm", "Change Trace", None))
        self.launchBtn.setText(_translate("SimInitForm", "LAUNCH", None))
        self.cancelBtn.setText(_translate("SimInitForm", "CANCEL", None))
        self.indexMaxIncreaseButton.setText(_translate("SimInitForm", "+", None))
        self.indexMaxDecreaseButton.setText(_translate("SimInitForm", "--", None))
        self.indexDecreaseButton.setText(_translate("SimInitForm", "<-", None))
        self.queueIndexSlotEdit.setText(_translate("SimInitForm", "1", None))
        self.frameRateEdit.setText(_translate("SimInitForm", "24.0", None))
        self.indexIncreaseButton.setText(_translate("SimInitForm", "->", None))
        self.parallelSimsEdit.setText(_translate("SimInitForm", "1", None))
        self.parallelSimsLbl.setText(_translate("SimInitForm", "Parallel Sims", None))
        self.AuxLabel1.setText(_translate("SimInitForm", "Please note:\n"
"The \"Drop if >\" option for scalable video assumes\n"
"that the base layer is layer 1. Thus, if you \"Drop if > 1\",\n"
"you\'re dropping everything except the base layer.", None))
        self.dbaGatedVideoBtn.setText(_translate("SimInitForm", "GATED", None))
        self.dbaFixedVideoBtn.setText(_translate("SimInitForm", "FIXED", None))
        self.dbaLimitedVideoBtn.setText(_translate("SimInitForm", "LIMITED", None))
        self.label.setText(_translate("SimInitForm", "Grant Sizing (Video)", None))
        self.dbaGatedBtn.setText(_translate("SimInitForm", "GATED", None))
        self.dbaFixedBtn.setText(_translate("SimInitForm", "FIXED", None))
        self.dbaExcessBtn.setText(_translate("SimInitForm", "EXCESS", None))
        self.dbaLimitedBtn.setText(_translate("SimInitForm", "LIMITED", None))
        self.label_2.setText(_translate("SimInitForm", "Grant Sizing (Data)", None))
        self.lfjsptBtn.setText(_translate("SimInitForm", "LFJ-SPT", None))
        self.lfjlnfBtn.setText(_translate("SimInitForm", "LFJ-LNF", None))
        self.lpdBtn.setText(_translate("SimInitForm", "LPD", None))
        self.lfjBtn.setText(_translate("SimInitForm", "LFJ", None))
        self.apsBtn.setText(_translate("SimInitForm", "APS", None))
        self.jitEafBtn.setText(_translate("SimInitForm", "JIT EAF", None))
        self.jitEaafBtn.setText(_translate("SimInitForm", "JIT EAAF", None))
        self.eaafBtn.setText(_translate("SimInitForm", "EAAF", None))
        self.jitLpdBtn.setText(_translate("SimInitForm", "JIT LPD", None))
        self.intvlLfjlptBtn.setText(_translate("SimInitForm", "INTVL LFJ-LPT", None))
        self.spdLptBtn.setText(_translate("SimInitForm", "SPD-LPT", None))
        self.jitTestBtn.setText(_translate("SimInitForm", "JIT TEST", None))
        self.nascBtn.setText(_translate("SimInitForm", "NASC", None))
        self.ipactpsfBtn.setText(_translate("SimInitForm", "IPACT-PSF", None))
        self.jitSpdBtn.setText(_translate("SimInitForm", "JIT SPD", None))
        self.intvlLfjsptBtn.setText(_translate("SimInitForm", "INTVL LFJ-SPT", None))
        self.jitLfjsptBtn.setText(_translate("SimInitForm", "JIT LFJ-SPT", None))
        self.eafBtn.setText(_translate("SimInitForm", "EAF", None))
        self.ipactBtn.setText(_translate("SimInitForm", "IPACT", None))
        self.intvlEafBtn.setText(_translate("SimInitForm", "INTVL EAF", None))
        self.jitLfjlptBtn.setText(_translate("SimInitForm", "JIT LFJ-LPT", None))
        self.spdBtn.setText(_translate("SimInitForm", "SPD", None))
        self.leastAssignedBtn.setText(_translate("SimInitForm", "Least Assigned", None))
        self.intvlEaafBtn.setText(_translate("SimInitForm", "INTVL EAAF", None))
        self.intvlLfjlnfBtn.setText(_translate("SimInitForm", "INTVL LFJ-LNF", None))
        self.jitLfjlnfBtn.setText(_translate("SimInitForm", "JIT LFJ-LNF", None))
        self.lfjlptBtn.setText(_translate("SimInitForm", "LFJ-LPT", None))
        self.textLabel5_2.setText(_translate("SimInitForm", "Misc", None))
        self.textLabel4_2.setText(_translate("SimInitForm", "Online JIT", None))
        self.textLabel3_2.setText(_translate("SimInitForm", "Online Interval", None))
        self.textLabel2_2.setText(_translate("SimInitForm", "Offline", None))
        self.label_3.setText(_translate("SimInitForm", "Grant Scheduling", None))
        self.timeShiftLbl_2.setText(_translate("SimInitForm", "Time Shift (ms):", None))
        self.timeShiftEdit.setText(_translate("SimInitForm", "0.0", None))
        self.vsOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.vsOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.label_4.setText(_translate("SimInitForm", "Random Video Start", None))
        self.PredTypeEdit.setText(_translate("SimInitForm", "FFBI", None))
        self.pvtOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.PredTypeLbl_2.setText(_translate("SimInitForm", "Pred. Type:", None))
        self.pvtOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.label_5.setText(_translate("SimInitForm", "Predict Video Traffic", None))
        self.label_6.setText(_translate("SimInitForm", "Video Traffic", None))
        self.label_7.setText(_translate("SimInitForm", "Data Traffic Type", None))
        self.label_8.setText(_translate("SimInitForm", "TIME_TRACE", None))
        self.label_9.setText(_translate("SimInitForm", "GRANT_TRACE", None))
        self.label_10.setText(_translate("SimInitForm", "GET_TAIL", None))
        self.label_11.setText(_translate("SimInitForm", "Scalable Video", None))
        self.svOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.svOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.gtOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.gtOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.grtOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.grtOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.ttOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.ttOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.ssBtn.setText(_translate("SimInitForm", "Self-Similar", None))
        self.pnBtn.setText(_translate("SimInitForm", "Poisson", None))
        self.vtOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.vtOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.maxGrantSizeLbl.setText(_translate("SimInitForm", "MAX_GRANT_SIZE", None))
        self.fixedGrantSizeLbl.setText(_translate("SimInitForm", "FIXED_GRANT_SIZE", None))
        self.label_12.setText(_translate("SimInitForm", "Grant Sizing Parameters", None))
        self.svDropStepThreshold.setText(_translate("SimInitForm", "Step", None))
        self.svDropStep_NumMAValues.setText(_translate("SimInitForm", "5", None))
        self.svDropStepMinBound.setText(_translate("SimInitForm", "0.0005", None))
        self.svDropDynamic.setText(_translate("SimInitForm", "Dynamic", None))
        self.svDropDynamic_2.setText(_translate("SimInitForm", "Dynamic", None))
        self.svDropNone.setText(_translate("SimInitForm", "None", None))
        self.svDropThresholdEdit.setText(_translate("SimInitForm", "4", None))
        self.svDropSensitivity.setText(_translate("SimInitForm", "1.0", None))
        self.svDropMaxBoundLabel.setText(_translate("SimInitForm", "Max Bound", None))
        self.svDropStepMaxBound.setText(_translate("SimInitForm", "0.005", None))
        self.svDropMinBoundLabel.setText(_translate("SimInitForm", "Min Bound", None))
        self.svDropThreshold_2.setText(_translate("SimInitForm", "Drop if >", None))
        self.svDropNone_2.setText(_translate("SimInitForm", "None", None))
        self.svDropThreshold.setText(_translate("SimInitForm", "Drop if >", None))
        self.label_13.setText(_translate("SimInitForm", "SV Packet Dropping", None))
        self.label_14.setText(_translate("SimInitForm", "FIXED_PROP_DELAY", None))
        self.fpdOnBtn.setText(_translate("SimInitForm", "ON", None))
        self.fpdOffBtn.setText(_translate("SimInitForm", "OFF", None))
        self.label_15.setText(_translate("SimInitForm", "WDM Type", None))
        self.fixedBtn.setText(_translate("SimInitForm", "Fixed Array", None))
        self.tunableBtn.setText(_translate("SimInitForm", "Tunable", None))
        self.runsLbl.setText(_translate("SimInitForm", "NUM_RUNS", None))
        self.fpdValueLbl.setText(_translate("SimInitForm", "PROP_DELAY_VALUE", None))
        self.numLhWdmONULbl.setText(_translate("SimInitForm", "NUM_LH_WDM_ONU", None))
        self.heavyLoadLbl.setText(_translate("SimInitForm", "HEAVY_LOAD", None))
        self.linkSpdLbl.setText(_translate("SimInitForm", "LINK_SPEED", None))
        self.numUhWdmONULbl.setText(_translate("SimInitForm", "NUM_UH_WDM_ONU", None))
        self.numHvyONULbl.setText(_translate("SimInitForm", "NUM_HEAVY_ONU", None))
        self.numWdmONULbl.setText(_translate("SimInitForm", "NUM_WDM_ONU", None))
        self.grdTimeLbl.setText(_translate("SimInitForm", "GUARD_TIME", None))
        self.simTimeLbl.setText(_translate("SimInitForm", "SIM_TIME", None))
        self.numONULbl.setText(_translate("SimInitForm", "NUM_ONU", None))
        self.maxPropDelayLbl.setText(_translate("SimInitForm", "MAX_PROP_DELAY", None))
        self.tuningTimeLbl.setText(_translate("SimInitForm", "TUNING_TIME", None))
        self.label_16.setText(_translate("SimInitForm", "Network Parameters", None))
        self.numStrmsLbl.setText(_translate("SimInitForm", "NUM_STREAMS", None))
        self.hurstParamLbl.setText(_translate("SimInitForm", "HURST_PARAM", None))
        self.label_17.setText(_translate("SimInitForm", "Self-Similar Parameters", None))
        self.endLoadLbl.setText(_translate("SimInitForm", "END_LOAD", None))
        self.loadIncrLbl.setText(_translate("SimInitForm", "LOAD_INCR", None))
        self.startLoadLbl.setText(_translate("SimInitForm", "START_LOAD", None))
        self.label_18.setText(_translate("SimInitForm", "Load Parameters", None))
        self.startLambdaLbl.setText(_translate("SimInitForm", "START_LAMBDA", None))
        self.endLambdaLbl.setText(_translate("SimInitForm", "END_LAMBDA", None))
        self.label_19.setText(_translate("SimInitForm", "Lambda Parameters", None))
        self.schedulerSlotSizeLbl.setText(_translate("SimInitForm", "SCHEDULER_SLOT_SIZE", None))
        self.starveThreshLbl.setText(_translate("SimInitForm", "STARVE_THRESH", None))
        self.schedulerNumSlotLbl.setText(_translate("SimInitForm", "SCHEDULER_NUM_SLOT", None))
        self.schedulerMaxWinChkBox.setText(_translate("SimInitForm", "SCHEDULER_MAX_WIN", None))
        self.acwLbl.setText(_translate("SimInitForm", "AVAIL_COST_WEIGHT", None))
        self.npoLbl.setText(_translate("SimInitForm", "NUM_PREFERRED_ONU", None))
        self.label_20.setText(_translate("SimInitForm", "Grant Scheduling Parameters", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SimInitForm = QtGui.QWidget()
    ui = Ui_SimInitForm()
    ui.setupUi(SimInitForm)
    SimInitForm.show()
    sys.exit(app.exec_())

