# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simviewform.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SimViewForm(object):
    def setupUi(self, SimViewForm):
        SimViewForm.setObjectName(_fromUtf8("SimViewForm"))
        SimViewForm.resize(897, 639)
        self.maxXEdit = QtGui.QLineEdit(SimViewForm)
        self.maxXEdit.setGeometry(QtCore.QRect(100, 150, 70, 23))
        font = QtGui.QFont()
        self.maxXEdit.setFont(font)
        self.maxXEdit.setObjectName(_fromUtf8("maxXEdit"))
        self.minXEdit = QtGui.QLineEdit(SimViewForm)
        self.minXEdit.setGeometry(QtCore.QRect(100, 120, 70, 23))
        font = QtGui.QFont()
        self.minXEdit.setFont(font)
        self.minXEdit.setObjectName(_fromUtf8("minXEdit"))
        self.maxXLbl = QtGui.QLabel(SimViewForm)
        self.maxXLbl.setGeometry(QtCore.QRect(20, 150, 80, 20))
        font = QtGui.QFont()
        self.maxXLbl.setFont(font)
        self.maxXLbl.setWordWrap(False)
        self.maxXLbl.setObjectName(_fromUtf8("maxXLbl"))
        self.hostEdit = QtGui.QLineEdit(SimViewForm)
        self.hostEdit.setGeometry(QtCore.QRect(60, 50, 125, 23))
        self.hostEdit.setObjectName(_fromUtf8("hostEdit"))
        self.plotCaptionEdit = QtGui.QLineEdit(SimViewForm)
        self.plotCaptionEdit.setGeometry(QtCore.QRect(290, 50, 290, 21))
        self.plotCaptionEdit.setObjectName(_fromUtf8("plotCaptionEdit"))
        self.maxYLbl = QtGui.QLabel(SimViewForm)
        self.maxYLbl.setGeometry(QtCore.QRect(20, 210, 80, 20))
        font = QtGui.QFont()
        self.maxYLbl.setFont(font)
        self.maxYLbl.setWordWrap(False)
        self.maxYLbl.setObjectName(_fromUtf8("maxYLbl"))
        self.maxYEdit = QtGui.QLineEdit(SimViewForm)
        self.maxYEdit.setGeometry(QtCore.QRect(100, 210, 70, 23))
        font = QtGui.QFont()
        self.maxYEdit.setFont(font)
        self.maxYEdit.setObjectName(_fromUtf8("maxYEdit"))
        self.minYEdit = QtGui.QLineEdit(SimViewForm)
        self.minYEdit.setGeometry(QtCore.QRect(100, 180, 70, 23))
        font = QtGui.QFont()
        self.minYEdit.setFont(font)
        self.minYEdit.setObjectName(_fromUtf8("minYEdit"))
        self.minYLbl = QtGui.QLabel(SimViewForm)
        self.minYLbl.setGeometry(QtCore.QRect(20, 180, 80, 20))
        font = QtGui.QFont()
        self.minYLbl.setFont(font)
        self.minYLbl.setWordWrap(False)
        self.minYLbl.setObjectName(_fromUtf8("minYLbl"))
        self.exportOutputBtn = QtGui.QPushButton(SimViewForm)
        self.exportOutputBtn.setGeometry(QtCore.QRect(180, 600, 150, 30))
        font = QtGui.QFont()
        self.exportOutputBtn.setFont(font)
        self.exportOutputBtn.setObjectName(_fromUtf8("exportOutputBtn"))
        self.viewParamsBtn = QtGui.QPushButton(SimViewForm)
        self.viewParamsBtn.setGeometry(QtCore.QRect(350, 600, 110, 30))
        font = QtGui.QFont()
        self.viewParamsBtn.setFont(font)
        self.viewParamsBtn.setObjectName(_fromUtf8("viewParamsBtn"))
        self.exitBtn = QtGui.QPushButton(SimViewForm)
        self.exitBtn.setGeometry(QtCore.QRect(590, 600, 87, 30))
        font = QtGui.QFont()
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName(_fromUtf8("exitBtn"))
        self.viewOutputBtn = QtGui.QPushButton(SimViewForm)
        self.viewOutputBtn.setGeometry(QtCore.QRect(20, 600, 140, 30))
        font = QtGui.QFont()
        self.viewOutputBtn.setFont(font)
        self.viewOutputBtn.setObjectName(_fromUtf8("viewOutputBtn"))
        self.stopSimBtn = QtGui.QPushButton(SimViewForm)
        self.stopSimBtn.setGeometry(QtCore.QRect(480, 600, 93, 29))
        font = QtGui.QFont()
        self.stopSimBtn.setFont(font)
        self.stopSimBtn.setObjectName(_fromUtf8("stopSimBtn"))
        self.confIntvlChkBox = QtGui.QCheckBox(SimViewForm)
        self.confIntvlChkBox.setGeometry(QtCore.QRect(20, 240, 160, 21))
        font = QtGui.QFont()
        self.confIntvlChkBox.setFont(font)
        self.confIntvlChkBox.setObjectName(_fromUtf8("confIntvlChkBox"))
        self.minXLbl = QtGui.QLabel(SimViewForm)
        self.minXLbl.setGeometry(QtCore.QRect(20, 120, 80, 20))
        font = QtGui.QFont()
        self.minXLbl.setFont(font)
        self.minXLbl.setWordWrap(False)
        self.minXLbl.setObjectName(_fromUtf8("minXLbl"))
        self.plotRefreshChkBox = QtGui.QCheckBox(SimViewForm)
        self.plotRefreshChkBox.setGeometry(QtCore.QRect(20, 270, 150, 22))
        font = QtGui.QFont()
        self.plotRefreshChkBox.setFont(font)
        self.plotRefreshChkBox.setObjectName(_fromUtf8("plotRefreshChkBox"))
        self.simOutputLbl = QtGui.QLabel(SimViewForm)
        self.simOutputLbl.setGeometry(QtCore.QRect(30, 300, 170, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.simOutputLbl.setFont(font)
        self.simOutputLbl.setWordWrap(False)
        self.simOutputLbl.setObjectName(_fromUtf8("simOutputLbl"))
        self.simIDLbl = QtGui.QLabel(SimViewForm)
        self.simIDLbl.setGeometry(QtCore.QRect(10, 10, 90, 20))
        font = QtGui.QFont()
        self.simIDLbl.setFont(font)
        self.simIDLbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.simIDLbl.setFrameShadow(QtGui.QFrame.Plain)
        self.simIDLbl.setWordWrap(False)
        self.simIDLbl.setObjectName(_fromUtf8("simIDLbl"))
        self.simIDEdit = QtGui.QLineEdit(SimViewForm)
        self.simIDEdit.setGeometry(QtCore.QRect(110, 10, 125, 23))
        self.simIDEdit.setObjectName(_fromUtf8("simIDEdit"))
        self.plotNameLbl = QtGui.QLabel(SimViewForm)
        self.plotNameLbl.setGeometry(QtCore.QRect(270, 10, 70, 20))
        font = QtGui.QFont()
        self.plotNameLbl.setFont(font)
        self.plotNameLbl.setWordWrap(False)
        self.plotNameLbl.setObjectName(_fromUtf8("plotNameLbl"))
        self.hostLbl = QtGui.QLabel(SimViewForm)
        self.hostLbl.setGeometry(QtCore.QRect(10, 50, 40, 20))
        font = QtGui.QFont()
        self.hostLbl.setFont(font)
        self.hostLbl.setWordWrap(False)
        self.hostLbl.setObjectName(_fromUtf8("hostLbl"))
        self.plotCaptionLbl = QtGui.QLabel(SimViewForm)
        self.plotCaptionLbl.setGeometry(QtCore.QRect(200, 50, 80, 20))
        font = QtGui.QFont()
        self.plotCaptionLbl.setFont(font)
        self.plotCaptionLbl.setWordWrap(False)
        self.plotCaptionLbl.setObjectName(_fromUtf8("plotCaptionLbl"))
        self.simStatusLbl = QtGui.QLabel(SimViewForm)
        self.simStatusLbl.setGeometry(QtCore.QRect(160, 90, 110, 20))
        font = QtGui.QFont()
        self.simStatusLbl.setFont(font)
        self.simStatusLbl.setWordWrap(False)
        self.simStatusLbl.setObjectName(_fromUtf8("simStatusLbl"))
        self.simStatusTitleLbl = QtGui.QLabel(SimViewForm)
        self.simStatusTitleLbl.setGeometry(QtCore.QRect(10, 90, 130, 20))
        font = QtGui.QFont()
        self.simStatusTitleLbl.setFont(font)
        self.simStatusTitleLbl.setWordWrap(False)
        self.simStatusTitleLbl.setObjectName(_fromUtf8("simStatusTitleLbl"))
        self.plotNameEdit = QtGui.QLineEdit(SimViewForm)
        self.plotNameEdit.setGeometry(QtCore.QRect(360, 10, 125, 23))
        self.plotNameEdit.setObjectName(_fromUtf8("plotNameEdit"))
        self.pushButtonAutoName = QtGui.QPushButton(SimViewForm)
        self.pushButtonAutoName.setGeometry(QtCore.QRect(500, 10, 21, 21))
        self.pushButtonAutoName.setText(_fromUtf8(""))
        self.pushButtonAutoName.setObjectName(_fromUtf8("pushButtonAutoName"))
        self.grantsizePVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.grantsizePVsLoadBtn.setGeometry(QtCore.QRect(220, 260, 150, 20))
        self.grantsizePVsLoadBtn.setObjectName(_fromUtf8("grantsizePVsLoadBtn"))
        self.buttonGroup = QtGui.QButtonGroup(SimViewForm)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.grantsizePVsLoadBtn)
        self.utilVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.utilVsLoadBtn.setGeometry(QtCore.QRect(220, 170, 140, 20))
        self.utilVsLoadBtn.setObjectName(_fromUtf8("utilVsLoadBtn"))
        self.buttonGroup.addButton(self.utilVsLoadBtn)
        self.delayVsONUBtn = QtGui.QRadioButton(SimViewForm)
        self.delayVsONUBtn.setGeometry(QtCore.QRect(530, 230, 120, 20))
        self.delayVsONUBtn.setObjectName(_fromUtf8("delayVsONUBtn"))
        self.buttonGroup.addButton(self.delayVsONUBtn)
        self.histBtn = QtGui.QRadioButton(SimViewForm)
        self.histBtn.setGeometry(QtCore.QRect(530, 140, 105, 21))
        self.histBtn.setObjectName(_fromUtf8("histBtn"))
        self.buttonGroup.addButton(self.histBtn)
        self.grantsizeVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.grantsizeVsLoadBtn.setGeometry(QtCore.QRect(220, 230, 150, 20))
        self.grantsizeVsLoadBtn.setObjectName(_fromUtf8("grantsizeVsLoadBtn"))
        self.buttonGroup.addButton(self.grantsizeVsLoadBtn)
        self.timeHistBtn = QtGui.QRadioButton(SimViewForm)
        self.timeHistBtn.setGeometry(QtCore.QRect(530, 170, 140, 21))
        self.timeHistBtn.setObjectName(_fromUtf8("timeHistBtn"))
        self.buttonGroup.addButton(self.timeHistBtn)
        self.byteHistBtn = QtGui.QRadioButton(SimViewForm)
        self.byteHistBtn.setGeometry(QtCore.QRect(530, 200, 130, 21))
        self.byteHistBtn.setObjectName(_fromUtf8("byteHistBtn"))
        self.buttonGroup.addButton(self.byteHistBtn)
        self.delayVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.delayVsLoadBtn.setGeometry(QtCore.QRect(220, 140, 120, 20))
        self.delayVsLoadBtn.setObjectName(_fromUtf8("delayVsLoadBtn"))
        self.buttonGroup.addButton(self.delayVsLoadBtn)
        self.tputVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.tputVsLoadBtn.setGeometry(QtCore.QRect(370, 200, 160, 20))
        self.tputVsLoadBtn.setObjectName(_fromUtf8("tputVsLoadBtn"))
        self.buttonGroup.addButton(self.tputVsLoadBtn)
        self.nzrVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.nzrVsLoadBtn.setGeometry(QtCore.QRect(370, 170, 120, 20))
        self.nzrVsLoadBtn.setObjectName(_fromUtf8("nzrVsLoadBtn"))
        self.buttonGroup.addButton(self.nzrVsLoadBtn)
        self.reportsizeVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.reportsizeVsLoadBtn.setGeometry(QtCore.QRect(220, 290, 150, 20))
        self.reportsizeVsLoadBtn.setObjectName(_fromUtf8("reportsizeVsLoadBtn"))
        self.buttonGroup.addButton(self.reportsizeVsLoadBtn)
        self.cyclelenVsONUBtn = QtGui.QRadioButton(SimViewForm)
        self.cyclelenVsONUBtn.setGeometry(QtCore.QRect(530, 260, 150, 20))
        self.cyclelenVsONUBtn.setObjectName(_fromUtf8("cyclelenVsONUBtn"))
        self.buttonGroup.addButton(self.cyclelenVsONUBtn)
        self.cyclelenVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.cyclelenVsLoadBtn.setGeometry(QtCore.QRect(220, 200, 150, 20))
        self.cyclelenVsLoadBtn.setObjectName(_fromUtf8("cyclelenVsLoadBtn"))
        self.buttonGroup.addButton(self.cyclelenVsLoadBtn)
        self.jitterVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.jitterVsLoadBtn.setGeometry(QtCore.QRect(370, 290, 120, 20))
        self.jitterVsLoadBtn.setObjectName(_fromUtf8("jitterVsLoadBtn"))
        self.buttonGroup.addButton(self.jitterVsLoadBtn)
        self.nosVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.nosVsLoadBtn.setGeometry(QtCore.QRect(370, 230, 160, 20))
        self.nosVsLoadBtn.setObjectName(_fromUtf8("nosVsLoadBtn"))
        self.buttonGroup.addButton(self.nosVsLoadBtn)
        self.delayVsTimeBtn = QtGui.QRadioButton(SimViewForm)
        self.delayVsTimeBtn.setGeometry(QtCore.QRect(370, 260, 130, 22))
        self.delayVsTimeBtn.setObjectName(_fromUtf8("delayVsTimeBtn"))
        self.buttonGroup.addButton(self.delayVsTimeBtn)
        self.granttimeVsLoadBtn = QtGui.QRadioButton(SimViewForm)
        self.granttimeVsLoadBtn.setGeometry(QtCore.QRect(370, 140, 150, 20))
        self.granttimeVsLoadBtn.setObjectName(_fromUtf8("granttimeVsLoadBtn"))
        self.buttonGroup.addButton(self.granttimeVsLoadBtn)
        self.label = QtGui.QLabel(SimViewForm)
        self.label.setGeometry(QtCore.QRect(210, 112, 70, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.simViewListBox = QtGui.QListWidget(SimViewForm)
        self.simViewListBox.setGeometry(QtCore.QRect(30, 330, 651, 261))
        self.simViewListBox.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.simViewListBox.setObjectName(_fromUtf8("simViewListBox"))

        self.retranslateUi(SimViewForm)
        QtCore.QObject.connect(self.viewOutputBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimViewForm.viewOutputBtn_pressed)
        QtCore.QObject.connect(self.exportOutputBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimViewForm.exportOutputBtn_pressed)
        QtCore.QObject.connect(self.exitBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimViewForm.exitBtn_pressed)
        QtCore.QObject.connect(self.stopSimBtn, QtCore.SIGNAL(_fromUtf8("pressed()")), SimViewForm.stopSimBtn_pressed)
        QtCore.QObject.connect(self.pushButtonAutoName, QtCore.SIGNAL(_fromUtf8("pressed()")), SimViewForm.pushButtonAutoName_pressed)
        QtCore.QMetaObject.connectSlotsByName(SimViewForm)
        SimViewForm.setTabOrder(self.plotNameEdit, self.plotCaptionEdit)
        SimViewForm.setTabOrder(self.plotCaptionEdit, self.minXEdit)
        SimViewForm.setTabOrder(self.minXEdit, self.maxXEdit)
        SimViewForm.setTabOrder(self.maxXEdit, self.minYEdit)
        SimViewForm.setTabOrder(self.minYEdit, self.maxYEdit)
        SimViewForm.setTabOrder(self.maxYEdit, self.confIntvlChkBox)
        SimViewForm.setTabOrder(self.confIntvlChkBox, self.viewOutputBtn)
        SimViewForm.setTabOrder(self.viewOutputBtn, self.exportOutputBtn)
        SimViewForm.setTabOrder(self.exportOutputBtn, self.viewParamsBtn)
        SimViewForm.setTabOrder(self.viewParamsBtn, self.exitBtn)
        SimViewForm.setTabOrder(self.exitBtn, self.simIDEdit)
        SimViewForm.setTabOrder(self.simIDEdit, self.hostEdit)

    def retranslateUi(self, SimViewForm):
        SimViewForm.setWindowTitle(_translate("SimViewForm", "Simulation View", None))
        self.maxXLbl.setText(_translate("SimViewForm", "Max X value", None))
        self.maxYLbl.setText(_translate("SimViewForm", "Max Y value", None))
        self.minYLbl.setText(_translate("SimViewForm", "Min Y value", None))
        self.exportOutputBtn.setText(_translate("SimViewForm", "Export Selected Output", None))
        self.viewParamsBtn.setText(_translate("SimViewForm", "View Sim Params", None))
        self.exitBtn.setText(_translate("SimViewForm", "Exit", None))
        self.viewOutputBtn.setText(_translate("SimViewForm", "View Selected Output", None))
        self.stopSimBtn.setText(_translate("SimViewForm", "Stop Sim", None))
        self.confIntvlChkBox.setText(_translate("SimViewForm", "Confidence Intervals", None))
        self.minXLbl.setText(_translate("SimViewForm", "Min X value", None))
        self.plotRefreshChkBox.setText(_translate("SimViewForm", "Plot Refresh", None))
        self.simOutputLbl.setText(_translate("SimViewForm", "Simulation Output", None))
        self.simIDLbl.setText(_translate("SimViewForm", "Simulation ID", None))
        self.plotNameLbl.setText(_translate("SimViewForm", "Plot Name", None))
        self.hostLbl.setText(_translate("SimViewForm", "Host", None))
        self.plotCaptionLbl.setText(_translate("SimViewForm", "Plot Caption", None))
        self.simStatusLbl.setText(_translate("SimViewForm", "Status", None))
        self.simStatusTitleLbl.setText(_translate("SimViewForm", "Simulation Status:", None))
        self.grantsizePVsLoadBtn.setText(_translate("SimViewForm", "Grnt Sz Pkt vs. Ld", None))
        self.utilVsLoadBtn.setText(_translate("SimViewForm", "Utilization vs. Load", None))
        self.delayVsONUBtn.setText(_translate("SimViewForm", "Delay vs. ONU", None))
        self.histBtn.setText(_translate("SimViewForm", "Histogram", None))
        self.grantsizeVsLoadBtn.setText(_translate("SimViewForm", "Grant Size vs. Load", None))
        self.timeHistBtn.setText(_translate("SimViewForm", "Time Histogram", None))
        self.byteHistBtn.setText(_translate("SimViewForm", "Byte Histogram", None))
        self.delayVsLoadBtn.setText(_translate("SimViewForm", "Delay vs. Load", None))
        self.tputVsLoadBtn.setText(_translate("SimViewForm", "Throughput vs. Load", None))
        self.nzrVsLoadBtn.setText(_translate("SimViewForm", "NZR vs. Load", None))
        self.reportsizeVsLoadBtn.setText(_translate("SimViewForm", "Report Size vs. Load", None))
        self.cyclelenVsONUBtn.setText(_translate("SimViewForm", "Cycle Len vs. ONU", None))
        self.cyclelenVsLoadBtn.setText(_translate("SimViewForm", "Cycle Len vs. Load", None))
        self.jitterVsLoadBtn.setText(_translate("SimViewForm", "Jitter vs. Load", None))
        self.nosVsLoadBtn.setText(_translate("SimViewForm", "ONU Sched vs. Load", None))
        self.delayVsTimeBtn.setText(_translate("SimViewForm", "Delay vs. Time", None))
        self.granttimeVsLoadBtn.setText(_translate("SimViewForm", "Grant Time vs. Load", None))
        self.label.setText(_translate("SimViewForm", "Plot Type", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SimViewForm = QtGui.QWidget()
    ui = Ui_SimViewForm()
    ui.setupUi(SimViewForm)
    SimViewForm.show()
    sys.exit(app.exec_())

